### ISSUE TITLE
Coverage Information aus falscher Quelle

### ISSUE THREAD

**Issue by mbeh-ub** [hbz/laser-ygor#1]
Bei der Verarbeitung der angehängten Datei mit Ygor wir eine falsche coverage Information in das Ergebnis übernommnen:

* In der Quelldatei ([SpringerLink_500.csv.zip](https://github.com/hbz/laser-ygor/files/867360/SpringerLink_500.csv.zip)) ist die coverage Information durch die Spalte "date_first_issue_online" repräsentiert. (Was zugegeben etwas dünn ist, da hier i.d.R. nur eine Jahreszahl steht)
* In der generierten Datei steht dann eine andere Coverage-Information (die zwar ausführlicher aber leider
falsch ist). Vermutlich kommt die von der ZDB ?.

Getestet mit Ygor Version: 1.1 (commit: 2290a0d8)

[SpringerLink_500.csv.zip](https://github.com/hbz/laser-ygor/files/867360/SpringerLink_500.csv.zip)

**Comment by klodav** [comment]
Ygor übernimmt zur JSON-Generierung alle Informationen aus den API-Calls; also von der ZDB (hier über den Umweg vom GBV).

Beispiel: 
**Acta ethologica** (ZDB-ID: 1499105-6, date_first_issue_online: 2003)

ZDB-OPAC: http://dispatch.opac.d-nb.de/DB=1.1/CMD?ACT=SRCHA&IKT=8509&SRT=LST_ty&TRM=all+1499105-6

SRU: http://sru.gbv.de/gvk?version=1.2&operation=searchRetrieve&maximumRecords=10&recordSchema=picaxml&query=pica.zdb%3D1499105-6%20and%20(pica.mak=Obvz%20or%20pica.mak=Obv)&sortKeys=year,,1

Ygor liefert anhand der ausgewerteten PICA-Felder 009Px:
```
"coverage": [
                {
                    "coverageDepth": "Fulltext",
                    "coverageNote": "Deutschlandweit zug\u00e4nglich",
                    "embargo": "",
                    "endDate": "2002-12-31 23:59:59.000",
                    "endIssue": "",
                    "endVolume": "5",
                    "startDate": "1999-01-01 00:00:00.000",
                    "startIssue": "",
                    "startVolume": "2"
                }
            ]
```

**Comment by berndoberknapp** [comment]
Für den Titel ist das richtig, aber nicht für das konkrete Paket, denn hier kann der lizenzierte Zeitraum von dem Zeitraum, der in der ZDB verzeichnet ist, abweichen. Wenn in der hochgeladenen Datei ein abweichender Zeitraum angegeben ist, muss dieser also verwendet werden, im Beispiel 2003ff statt der Nationallizenz.

**Comment by berndoberknapp** [comment]
Für den Titel dürfte die Angabe zur Nationallizenz übrigens auch nicht korrekt sein, da es sich dabei um ein spezielles Paket handelt. Beim Titel sollten ja vermutlich die grundsätzlich auf den Plattformen verfügbaren Zeiträume angegeben sein.

**Comment by darupp** [comment]
Ja, das haben wir eben auch festgestellt. Wir müssen uns noch überlegen, wie wir das handhaben. Im Augenblick haben wir das Coverage deaktiviert, damit keine falschen Daten in die GOKb gelangen.

**Comment by klodav** [comment]
Version 0.13 ist deployed.

**Comment by klodav** [comment]
Version 0.20

Folgende Coverage-Informationen werden aus den nun obligatorischen KBART-Dateien bezogen:

```
date_first_issue_online
date_last_issue_online
num_first_vol_online
num_last_vol_online
num_first_issue_online
num_last_issue_online
embargo_info
coverage_depth
notes

title_url
```

**Comment by klodav** [comment]
Version 0.21

Korrektur einer KBART-Feldbezeichnung: _coverage_notes_ anstatt _notes_
