### ISSUE TITLE
Unterstützung für mehrere Plattformen in einem Paket

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#10]
Einige Tipps in Paketen haben andere Plattformen. Das muss berücksichtigt werden. Hier ist auch das Plattform-Matching zu berücksichtigen.

**Comment by philboeselager** [comment]
@darupp : Gibt es ein konkretes Beispiel hierzu?

**Comment by philboeselager** [comment]
Aufgrund eines weiteren unklaren [Fehlers](https://github.com/hbz/laser-ygor/issues/13) konnte dieses Issue bislang nicht getestet bzw. bearbeitet werden. Als Ansatzpunkt habe ich bislang [JsonTransformer, Zeile 188](https://github.com/hbz/laser-ygor/blob/master/src/groovy/de/hbznrw/ygor/export/JsonTransformer.groovy#L188) identifiziert.

**Comment by philboeselager** [comment]
@darupp : Letztlich ja eine Dublette von #21, richtig? Dann bitte schließen.

**Comment by darupp** [comment]
Wg. Dublette geschlossen.
