### ISSUE TITLE
ISIL (ZDB Sigel) 

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#102]
The manual input-field for the ISIL (ZDB-Sigel) is not processed correctly: In GOKb, it is put under "Alternate Name" as alternate package name and not - as it should be - as package identifier under the Namespace ISIL.

**Comment by hemmefelix** [comment]
Fixing this issue seems important as more librarians are going to use the package upload via Ygor. Example: Partial packages with different names are thrown together if they have the same ZDB ISIL. Springer:Ebooks:ComputerScience:2017, 2018 and 2019 (ZDB-2-SCS) were imported individually and landed in one package in GOKbT. This is due to secondary matching on alternative names.

**Comment by darupp** [comment]
Reopened 

In 0.88 of YGOR the ZDB Sigel is STILL not processed or does at least not appear in the package JSON.

Tested on phaeton-dev

```
  "packageHeader" : {
    "breakable" : "No",
    "consistent" : "Yes",
    "fixed" : "Yes",
    "global" : "Global",
    "listStatus" : "In Progress",
    "nominalProvider" : "Emerald Group Publishing Limited",
    "paymentType" : "",
    "scope" : "",
    "userListVerifier" : "",
    "name" : "Emerald Management 120 KURZ Testpaket 2020-03-13",
    "nominalPlatform" : {
      "name" : "Emerald Insight",
      "primaryUrl" : "https://www.emerald.com/insight"
    },
    "curatoryGroups" : [ "hbz" ],
    "identifiers" : [ {
      "type" : "emerald",
      "value" : "EMX120"
    } ],
    "additionalProperties" : [ ],
    "soure" : { }
},
```

**Comment by darupp** [comment]
As of YGOR 0.89 `ZDB Sigel` is still not processed.

**Comment by philboeselager** [comment]
@darupp Which result do you expect? Current result is

	"packageHeader" : {
	  ...
	  "identifiers" : [ {
	    "type" : "isil",
	    "value" : "the value that you've entered"
	  } ],
	  ...
	}

in package Json.

**Comment by darupp** [comment]
This would be correct, but in my test cases, this does not work. 
Test scenario: 
`Titel` = Pakettitel
`Paketsigel (ISIL) der ZDB` = ZDB-55-EM120X
`Interner Paket-Identifikator` =  EMX120X // Namespace: emerald
`GOKb Plattform` = Emerald Insight
`GOKb Provider`= Emerald Group Publishing Limited
`Namensraum für proprietären Titel-Identifkator des Providers (title_id)`= emerald

```
 "identifiers" : [ {
      "type" : "emerald",
      "value" : "EMX120X"
    } ],
```
[EM 120.zip](https://github.com/hbz/laser-ygor/files/4375625/EM.120.zip)

Could it be that it doesn't work if an `Interner Paket-Identifikator`  is set?
