### ISSUE TITLE
Not selecting title_id namespace adds empty value to JSON

### ISSUE THREAD

**Issue by hornmo** [hbz/laser-ygor#105]
As of 81603d590069a8f252dd6d89b283a831752fc7af if no namespace is selected for title_id, the identifier is still added to the JSON as `{"type": "", "value": the_id_value}`, and therefore any GOKb import will fail.

**Comment by philboeselager** [comment]
Thanks for info! What behavior would do you expect, @hornmo & @darupp ?

**Comment by darupp** [comment]
if no namespace is selected, the identifier should not be inserted into the JSON.

**Comment by philboeselager** [comment]
A bit confusion here. If no namespace is selected in the ui select `namespace_title_id` I can not proceed or process any data. (Using Chrome.) This should prevent the behaviour described above.

How did you get to this situation, @hornmo ?

**Comment by hornmo** [comment]
TBH I am not able to reproduce this any more. If anything, I'm not sure if the selection _should_ be mandatory (for journals).

**Comment by darupp** [comment]
In my opinion, the title_id should not be mandatory, as especially for journals we have quite a lot of mandatory ids like online_identifier. Sometimes title_id is a mere doublette.

**Comment by philboeselager** [comment]
OK, so I'm going to make the title id namespace optional and drop the identifier field

- in case it is empty for a specific title and
- in case no namespace was selected

**Comment by hornmo** [comment]
That sounds good to me.
