### ISSUE TITLE
Accept "Volltext" for coverage_depth

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#107]
coverage_depth: German "volltext" should be accepted and translated to "fulltext" in JSON, there will be evaluated whether there are also german translations of "selected articles" and "abstracts" in use.

**Comment by darupp** [comment]
Should mapped in YGOR from "Volltext" to "fulltext", as the API already accepts "fulltext".

**Comment by VolkerHBZ** [comment]
done
