### ISSUE TITLE
ZDB-IDs von Print-Ausgaben

### ISSUE THREAD

**Issue by hornmo** [hbz/laser-ygor#11]
In der aktuellen Produktionsinstanz der GOKb tauchen ZDB-IDs der gedruckten Parallelausgaben im Namespace "zdb" auf (und es wurden ReviewRequests dazu erzeugt). Bsp.: [dieser Titel](http://phaeton.hbz-nrw.de/gokb/resource/show/org.gokb.cred.JournalInstance:784176)

[Dieser Titel](http://phaeton.hbz-nrw.de/gokb/resource/show/org.gokb.cred.TitleInstance%3A926895) hat als einzigen Identifier die ZDB-ID einer Print-Ausgabe und dürfte daher gar nicht in der GOKb existieren! Falls man davon ausgehen will, dass in diesem Fall eigentlich die Online-Ausgabe verzeichnet werden sollte (und in dem Paket enthalten ist), sollte man in der ZDB-Abfrage das Feld der Parallelausgabe (039D) auswerten, und den daraus entnommenen ZDB-Identifier zum Matchen verwenden. [SRU-Query dieses Print-Mediums](http://sru.gbv.de/zdbdb?version=1.2&operation=searchRetrieve&query=pica.yyy%3D201164-5&maximumRecords=10&recordSchema=picaxml)

Ich bin mir nicht sicher, wo die herkommen, weil bei den SRU-Abfragen alle gedruckten Ausgaben herausgefiltert werden sollten. Falls diese wirklich verzeichnet werden sollen, müsste man überlegen, ob man diese wie bei issn & eissn in einen gesonderten Namespace packt, und ob man diesen überhaupt als Primary zum matchen braucht.

**Comment by klodav** [comment]
Version 0.24

Die Ursache liegt vermutlich an der Nutzung der alternativen SRU-Schnittstelle des GBV. Das bisherige URL-Constraint zur Beschränkung der Antworten auf Online-Ressourcen funktioniert hier nicht mehr und Attribute/Identifikatoren werden ggfs. aus dem falschen Datensatz (print) übernommen.

**Comment by klodav** [comment]
Version 0.25

fixed
