### ISSUE TITLE
Titel mit Steuerzeichen aus der ZDB

### ISSUE THREAD

**Issue by hornmo** [hbz/laser-ygor#12]
In der ZDB werden Titel, die mit einem Artikel beginnen, mit dem Steuerzeichen '@' für die Sortierung versehen. Falls der Titel aus der ZDB übernommen wird, muss dieser auf das Steuerzeichen überprüft werden, und dieses entfernt werden.

Bsp.:
[The \@Botanical review (in GOKb)](http://phaeton.hbz-nrw.de/gokb/resource/show/org.gokb.cred.JournalInstance:899482) 
[Gleicher Titel per SRU](http://sru.gbv.de/zdbdb?version=1.2&operation=searchRetrieve&query=pica.yyy%3D2066026-1&maximumRecords=10&recordSchema=picaxml)

**Comment by philboeselager** [comment]
Done.

**Comment by darupp** [comment]
Problem tritt immer noch auf

**Comment by philboeselager** [comment]
@darupp Die beiden Links aus dem Originalpost funktionieren nicht mehr. Kannst Du ein neues Beispiel anfügen?

**Comment by darupp** [comment]
@philboeselager Die Testdatei, die ich gestern verschickt habe, hat entsprechende Steuerzeichen im "Title"-JSON eingefügt.

**Comment by philboeselager** [comment]
Behoben in https://github.com/hbz/laser-ygor/commit/c891971a1d1ddb3eb008b1aed6e19c866ea585d4.
