### ISSUE TITLE
Invalid SRU title histories are not discarded.

### ISSUE THREAD

**Issue by hornmo** [hbz/laser-ygor#129]
Currently, if a ZDB history link in 039E does not link to another title, an invalid history event will be created.

Example: Pharmacology – [1483550-2](http://services.dnb.de/sru/zdb?version=1.1&operation=searchRetrieve&query=dnb.zdbid=1483550-2%20and%20dnb.frm=O&maximumRecords=2&recordSchema=PicaPlus-xml)

In [EZB-NALJB-00504_Karger_Journals_Archiv_2019_05_13.txt](https://github.com/hbz/laser-ygor/files/3173845/EZB-NALJB-00504_Karger_Journals_Archiv_2019_05_13.txt)

```
<ppxml:tag id="039E" occ="">
    <ppxml:subf id="b">f</ppxml:subf>
    <ppxml:subf id="r">
        Vorg. ---> Medicina et pharmacologia experimentalis
    </ppxml:subf>
</ppxml:tag>
```

This results in
```
"historyEvents": [{
         "date": "1968-01-01 00:00:00.000",
         "from": [{
            "identifiers": [],
            "title": ""
         }],
         "to": [{
            "identifiers": [
               {
                  "type": "zdb",
                  "value": "1483550-2"
               },
               {
                  "type": "eissn",
                  "value": "1423-0313"
               }
            ],
            "title": "Pharmacology"
         }]
      }],
```

Not sure if this is an error in ZDB also, but Ygor should probably discard such events completely.

**Comment by darupp** [comment]
What should be the marker whether it should be discarded? I think the missing identifier in "from" or "to" could be a valid marker.
