### ISSUE TITLE
Informationsanreicherung schlägt fehl: "Mapping for notes not found"

### ISSUE THREAD

**Issue by philboeselager** [hbz/laser-ygor#13]
Die Informationsanreicherung schlägt mit einer scheinbar unlogischen Fehlermeldung fehl. Verwendeter Datensatz: 

    publication_title,print_identifier,online_identifier,date_first_issue_online,num_first_vol_online,num_first_issue_online,date_last_issue_online,num_last_vol_online,num_last_issue_online,title_url,first_author,title_id,embargo_info,coverage_depth,coverage_notes,publisher_name
    Abacus,0001-3072,1467-6281,1997,33,1,0,,,http://onlinelibrary.wiley.com/journal/10.1111/(ISSN)1467-6281/issues,,10.1111/(ISSN)1467-6281,,FullText,DummyCoverageNote,Wiley
    About Campus,1086-4822,1536-0687,1996,1,1,0,,,http://onlinelibrary.wiley.com/journal/10.1002/(ISSN)1536-0687/issues,,10.1002/(ISSN)1536-0687,,FullText,DummyCoverageNote,Wiley
    Academic Emergency Medicine,1069-6563,1553-2712,1997,4,1,0,,,http://onlinelibrary.wiley.com/journal/10.1111/(ISSN)1553-2712/issues,,10.1111/(ISSN)1553-2712,,FullText,DummyCoverageNote,Wiley
    Academic Review,1554-1142,1948-7177,2000,1,1,2002,2,1,http://onlinelibrary.wiley.com/journal/10.1111/(ISSN)1948-7177/issues,,10.1111/(ISSN)1948-7177a,,FullText,DummyCoverageNote,Wiley
    Accounting & Finance,0810-5391,1467-629X,1997,37,1,0,,,http://onlinelibrary.wiley.com/journal/10.1111/(ISSN)1467-629X/issues,,10.1111/(ISSN)1467-629X,,FullText,DummyCoverageNote,Wiley

Verwendete Einstellungen:

- Trennzeichen: Komma
- Plattform: Wiley Online Library
- Quellen: KBART, ZDB@GBV & EZB
- Schlüssel: eISSN

Fehlermeldung:

    java.lang.IllegalArgumentException: 
    Mapping for notes not found, expected one of [coverage_depth, coverage_notes, date_first_issue_online, date_last_issue_online, embargo_info, first_author, num_first_issue_online, num_first_vol_online, num_last_issue_online, num_last_vol_online, online_identifier, print_identifier, publication_title, publisher_name, title_id, title_url] 
    at org.apache.commons.csv.CSVRecord.get(CSVRecord.java:104)
    at org.apache.commons.csv.CSVRecord$get$0.call(Unknown Source)
    at de.hbznrw.ygor.processing.KbartProcessor$_initData_closure1$_closure3.doCall(KbartProcessor.groov

Verwendete Version: https://github.com/hbz/laser-ygor/commit/e6a0872a86c3fbd0780b5991913a6f8ea1bf4a68

**Comment by klodav** [comment]
KBART II setzt im Unterschied zu KBART I *notes* anstelle von *coverage_notes' voraus.
