### ISSUE TITLE
Ygor Statistic Improvements

### ISSUE THREAD

**Issue by MiriKon** [hbz/laser-ygor#131]
After having processed a KBART file via Ygor, it would be great if the Statistic section could be revised in order to see at once which titles have been removed. 

The "status" overview in the statistic shows which titles have been successfully processed by Ygor but the information **which** titles have been removed and will not be uploaded to the GOKb is not ideally presented yet as there is no information on the publication title, an identifier or the reason why the title has not been processed. It would also be really helpful if users would be able to click on the number of titles that have been removed (e.g. 4 titles in this screenshot) and immediately see **only** the exact list of titles that were problematic. 
![GOKB_9](https://user-images.githubusercontent.com/45172978/58545203-14fabc00-8203-11e9-9d9d-16bed279ca1b.JPG)

Instead of the technical information (e.g. VALIDATOR_IDENTIFIER_IS_INVALID), I would propose to give an exact reason/feedback why the title has been problematic (e.g. No ZDB ID or Missing eISSN etc.). 

I would also suggest to give the actual publication title from the KBART file instead of the annotation "faulty" (s. screenshot). The red coloring, though, is very helpful and should continue to be used. 

The red/blue/yellow "filters" in the statistic section are not really useful as most users will likely look at the "status". Therefore, the filters should be folded up, so that they don't confuse users but can still be viewed by expanding the "filter"-box.

**Comment by philboeselager** [comment]
Let me summarise and integrate with results from our planning with @darupp and @VolkerHBZ:

We want to:

- show titles that have been removed prominently, with
  - publication title, both from
    - Kbart &
    - ZDB-API (@MiriKon ?)
  - ids
  - exact / more specific and descriptive reason for removing, e. g. 
    - "missing ZDB-ID"
    - "missing eISSN"

- show a reduced list view optionally (with removed titles only). Our intention was to place these titles on top of the list always.

- keep the coloring scheme (red for "error", yellow for like "question" / GOKb review request, green (or blue) for "everything alright")

- make the result filters less irritating, e. g.
  - show them optionally only
  - show them less prominent

- show detailed TIPP/title view when clicking on item in list
  - possibly as overlay over the list

I would start with this draft and we can see afterwards if we need something else.

**Comment by MiriKon** [comment]
One minor addition for the Ygor improvements: it would be great if the buttons "package zur GOKb senden" and "titles zur GOKb senden" could be swapped so that the "titles"-button comes first.
![Ygor_Datenanreicherung](https://user-images.githubusercontent.com/45172978/59257347-0e723880-8c36-11e9-8eb5-5170b93348f2.JPG)
Right now, the order of the two buttons is slightly misleading as users have to upload the titles before the package.

**Comment by philboeselager** [comment]
@darupp @MiriKon Building the statistics, I came across the following questions:

- In which cases would we want titles / TIPPs to be removed (marked red in statistics)?
- In which cases would we want them to be marked as to be checked (yellow)?

Please list the most important cases. We can add further ones later, of course.

**Comment by philboeselager** [comment]
Rename status codes: [YGOR_Fehlermeldungen.txt](https://github.com/hbz/laser-ygor/files/3350213/YGOR_Fehlermeldungen.txt) as specified by @darupp and @MiriKon

**Comment by darupp** [comment]
Removed from Titles and TIPPs

  * APICALL_ZDB_NO_MATCH
  * APICALL_ZDB_MULTIPLE_MATCHES
  * VALIDATOR_IDENTIFIER_IS_MISSING (depends on implementation - if you get a correct api answer via _another_ identifier, title and tipp shouldn't be removed)
  * VALIDATOR_URL_IS_INVALID
  * VALIDATOR_URL_IS_NOT_ATOMIC
  * VALIDATOR_URL_IS_MISSING

**Comment by philboeselager** [comment]
TODO: Re-implement link cloud symbol to allow investigation of API calls (both, ZDB and EZB).
