### ISSUE TITLE
Bootstrap Template for user Roles

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#132]
At the Moment, after a new GOKb installation you have to edit the rights manually. This should be done in the Bootstrap.groovy according to this template: https://docs.google.com/document/d/1wxvLuwmaZyXwlE-SDO6JRHQ2hnLMosiZGykFmdMODUo/edit#heading=h.tfwkt66ewl10

**Comment by hornmo** [comment]
This is an issue for https://github.com/openlibraryenvironment/gokb.
