### ISSUE TITLE
File upload bugs

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#134]
Tested with 0.71

- "Delete File" and "Upload another file" don't work: 

>   An error has occurred
>  No signature of method: ygor.Enrichment.getFile() is applicable for argument types:  
> (ygor.Enrichment$FileType) values: [ORIGIN] Possible solutions: 
> getAsFile(ygor.Enrichment$FileType), getAll(), getDate(), getId(), getAll([Ljava.io.Serializable;), getAll(java.lang.Iterable)

**Comment by philboeselager** [comment]
Thanks. Fixed in https://github.com/hbz/laser-ygor/commit/2e4ae034e85205fdbf22277cc55f70cb8625dc94 and deployed on DEV.

**Comment by darupp** [comment]
- Doesn't find existing column headers

> Fehlende Spalten im CSV-Header: [date_first_issue_online, date_last_issue_online, num_first_vol_online, num_last_vol_online, num_first_issue_online, num_last_issue_online, title_url, embargo_info, coverage_depth, notes]
[OECD_Serials.csv.zip](https://github.com/hbz/laser-ygor/files/3349131/OECD_Serials.csv.zip)
