### ISSUE TITLE
Mapping of title_id to namespace

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#135]
* No selection must be possible 
  * Check if identifier is already in the JSON (so that no redundancies happen, i.e. the user maps e-issn to the namespace eissn although this is done automatically via the API call)
  * DOI

**Comment by philboeselager** [comment]
Further TODO:

- process format checks for title_id depending on ID type selected.
- map title_id to Json structure required by GOKb. (This is currently not yet specified in https://wiki1.hbz-nrw.de/pages/viewpage.action?pageId=182091855)

**Comment by philboeselager** [comment]
@darupp "eissn" and "issn" (which is "pissn" - right?) are currently displayed in the dropdown select box. Should they be filtered out?

**Comment by philboeselager** [comment]
@darupp Should doi's be normalized so that they always are presented as a URI?

**Comment by darupp** [comment]
@philboeselager 

- Yes, doi's should be normalized
- Yes, eissn and issn = pissn should be filtered out.

**Comment by darupp** [comment]
>     * map title_id to Json structure required by GOKb. (This is currently not yet specified in https://wiki1.hbz-nrw.de/pages/viewpage.action?pageId=182091855)

This is done in this part oft the title JSON

     "identifiers" : [
             {
                "type" : "eissn",
                "value" : "1520-6041"
             },
             {
                "type" : "zdb",
                "value" : "2006302-7"
             }
          ],

It should work if you simply add

             {
                "type" : "<selected title_id namespace>",
                "value" : "<title_id value from KBART file>"
             }

**Comment by philboeselager** [comment]
> It should work if you simply add
> 
> ```
>          {
>             "type" : "<selected title_id namespace>",
>             "value" : "<title_id value from KBART file>"
>          }
> ```

Yes. That's the way I'm implementing it.

**Comment by philboeselager** [comment]
Is implemented. Closing.
