### ISSUE TITLE
Character Encoding

### ISSUE THREAD

**Issue by philboeselager** [hbz/laser-ygor#139]
Ygor expects UTF-8 character encoding. For the likely case that data comes with any other encoding, we could implement a check like: as soon as Ygor detects a character that is not in the region of
`[a-zA-Z0-9]` (read as RegEx), a dialogue is opened that allows a selection of character encoding. The resulting data is visualized on time in the dialogue - this helps the user to figure out the best selection.
We should probably order some encoding sets with UTF-8 being preselected as first entry.

This check is only visualized once automatically per processing. Additionally, we might consider to give the opportunity to change the selection later.

In general, the earlier in the processing data the check takes place, the better. It should be best to check it even before querying (ZDB and EZB) APIs.

**Comment by croqueGrec09** [comment]
This issue is for LAS:eR interesting as well and I should develop code which does a character encoding check. The pull request/commit shall be referenced here.

**Comment by croqueGrec09** [comment]
On LAS:eR-side, the including resp. updating of the following library did the trick:

`runtime 'com.github.albfernandez:juniversalchardet:2.3.0'`

Check the BuildConfig equivalent in Ygor where to include this library.

Proceed then as follows:

`
String encoding = UniversalDetector.detectCharset(tsvFile.getInputStream())
if(encoding == "UTF-8") {
  //process file
}
else {
  //report error
}
`

**Comment by darupp** [comment]
Should be implemented in the method `uploadFile` in the `EnrichtmentController`.

**Comment by VolkerHBZ** [comment]
I'm on it.

**Comment by VolkerHBZ** [comment]
I'm on it.
done!
