### ISSUE TITLE
Normalisierung von URLs

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#14]
In der GOKb gibt es Matchingprobleme mit diversen URL-Formen, wenn sie einen trailing slash haben oder nicht, z.B. 
http://phaeton.hbz-nrw.de/gokb/resource/show/org.gokb.cred.Platform%3A66431
http://phaeton.hbz-nrw.de/gokb/resource/show/org.gokb.cred.Platform%3A1230144

In der GOKb sollte das Problem nicht behoben werden, da ansonsten das Matching zu lange dauern würde (siehe Mail von Moritz vom 12.09.2017). 

URL-Normalisierung in Ygor bitte so abändern, dass die __Domain-URL für __Plattformen__ (Domäne)__ grundsätzlich __ohne trailing slash__ geschrieben werden.

**Comment by philboeselager** [comment]
Done.
