### ISSUE TITLE
Error with UTF-8 encoding

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#147]
Correct UTF-8 files will sometimes produce an error 45

    Please use UTF-8 encoding for uploading data.

Saving as "UTF-8 with BOM" can help with the problem. 

This behaviour is erratic. Sometimes it happens, sometimes it accepts the very same file after a while. Tested with 0.60 on deploy http://phaeton-qa.hbz-nrw.de:9000/ygor/enrichment/process. 

Test files are attached (without knowing whether it will work this time)[https://app.zenhub.com/files/76962941/79c9909f-7aac-4593-a112-8e5d080eebc8/download](https://app.zenhub.com/files/76962941/79c9909f-7aac-4593-a112-8e5d080eebc8/download)

**Comment by philboeselager** [comment]
Tested both files on three different machines (local development, phaeton-dev, phaeton-qa). All runs were free of file upload problems. Seems to have been a little hick-up and is not reproducibile.

Anyhow, I've solved another little issue with this test data, see https://github.com/hbz/laser-ygor/commit/b098028df271f78b034a66337a3c2199f505b78c.

**Comment by VolkerHBZ** [comment]
the BOM problem should have been solved by line 49 in KbartRader.groovy...
