### ISSUE TITLE
Error with double column names in KBART file - correct error message

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#148]
Tested with double column name "access_type". 

YGOR first accepts the file, but when enriching the file via the ZDB API, the progress bar doesn't move a bit. 

A correct error message should be implemented such as "Double Column 'access_type' in KBART file", because this causality is near impossible to detect for a user.

**Comment by darupp** [comment]
[https://app.zenhub.com/files/76962941/64111c62-ec01-47eb-889a-2682957e2160/download](https://app.zenhub.com/files/76962941/64111c62-ec01-47eb-889a-2682957e2160/download)

**Comment by philboeselager** [comment]
By now (Ygor 0.86), the effect is an error message saying:

"Die Spalte mit der Überschrift access_type kommt mehrfach in der KBART-Datei vor. Bitte entfernen Sie die redundante Spalte oder fragen Sie den Anbieter nach einer Datei ohne Dubletten.
Sie können die aktuelle KBART-Spezifikation hier finden."

I think this is exactly what we would expect. Closing.
