### ISSUE TITLE
Title and Package Upload fails

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#149]
Tested with 0.60 on http://phaeton.hbz-nrw.de:9000/ygor/enrichment/process

Error Message after inserting the credentials: 

```
Unable to determine the current character, it is not a string, number, array, or object The current character read is '<' with an int value of 60 Unable to determine the current character, it is not a string, number, array, or object line number 1 index number 0 <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> ^

```
Also there are some UI errors:
- no "Save Debug file" button
- no "Save raw file" button.

[https://app.zenhub.com/files/76962941/2e5f7633-22d2-41c8-a545-bd80e07ab544/download](https://app.zenhub.com/files/76962941/2e5f7633-22d2-41c8-a545-bd80e07ab544/download)

**Comment by VolkerHBZ** [comment]
This error occurs when GOKb cannot accept the credentials and replies with the HTML-Login-Page instead of a JSON response. Not sure how to differentiate between a "normal" wrong login and the rejection of a JSON-Request.
