### ISSUE TITLE
Titelsplits: Zwei History events statt einem

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#15]
Im Augenblick wird nur ein history event bei einem Titelsplit erstellt. Es sollen zwei erstellt werden (Konvention in der Live-GOKb und von ZDB gewünscht). 

Beispiel: http://phaeton.hbz-nrw.de/gokb/resource/show/org.gokb.cred.JournalInstance%3A391627

**Comment by philboeselager** [comment]
@darupp : Was soll in dem zweiten History Event genau enthalten sein?

**Comment by philboeselager** [comment]
@darupp : Bitte um ein neues Beispiel.
