### ISSUE TITLE
Checking for possible Titlesplits in YGOR

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#151]
To prevent the import of titles with not acknowledged title splits (i.e. the creation of single titles in GOKb when in fact multiple titles should be created that are connected via title history events) there should be additional validation: 

  * When the date in "published from" is later than the date in "date_first_issue_online"
  * ?

... those titles should be excluded from the import with the message: 
"Publication start date later than coverage start date. There could be an unrecognized title split. Please check the title reference in ZDB and correct the ZDB record and/or the KBART record." 
"Das Feld 'publication start' hat ein früheres Datum als 'coverage start date'. Das könnte auf einen nicht erkannten Titlesplit hindeuten. Bitte prüfen Sie den Titel in der ZDB nach und korrigieren Sie ggf. den ZDB-Eintrag oder die Zeile in der KBART-Datei."

**Comment by philboeselager** [comment]
Needs further clarification concerning collaboration with ZDB.

**Comment by philboeselager** [comment]
This has not been an issue for 1,5 years and does not seem to be a such anymore. Hence closing.
If the problem still exists, please re-open and specify, where the message outlined above should occur.
