### ISSUE TITLE
Re-Evaluaton YGOR Workflow

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#156]
Zentrale Seite der Datenanreicheurng ist die neue Seite statistics/show.

**Aufbau**

  * Zentrale Fehlermeldungen (recordunabhängig) in Panel nach oben
  * Liste aller Records gruppiert nach gültigen und ungültigen
  * Listenaufbau
    * Name des Records aus dominanter Quelle
    * Link zu Record der jeweiligen Quelle bzw. Link unter ID der jeweiligen Quelle
    * Fehlerstatus (rotes Kreuz / grüner Haken) mit Tooltip/Popup, was der Fehler ist.

  *

**Comment by philboeselager** [comment]
@darupp Is there anything still to be done about this issue? I'm not sure whether I understand everything... let's talk about it.

**Comment by philboeselager** [comment]
As I think all this is done by now, I'm closing this issue.
