### ISSUE TITLE
E-Book Upload creates empty package json when only isbn is given 

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#157]
Regarding ebook import, tipps are lacking in the package json if there is only a print isbn. It can reproduced if you have only the *print_identifier* as identifier (pisbn in json), but don't map a namespace to *title_id*.

Tested on phaeton-qa, KBART and all files are attached: 
[https://app.zenhub.com/files/76962941/203e32b1-2793-4788-96cd-7ca26cc48a2b/download](https://app.zenhub.com/files/76962941/203e32b1-2793-4788-96cd-7ca26cc48a2b/download)

**Comment by philboeselager** [comment]
Works by now (Ygor 0.86). Closing.
