### ISSUE TITLE
API Call against GOKb for publisher matching

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#159]
Field publisherName: There could be an additional API Call to match existing GOKb organisations before sending the JSON to the GOKb via the crossreferencing API. The response could be shown in the statistics and be edited if there is no match.

**Comment by philboeselager** [comment]
@darupp Very good idea. The devil is in the details. There's some variety in publisher names in KBart files.

- GOKb: "Elsevier B.V." -- KBart: "Elsevier"
- GOKb: "Elsevier B.V." -- KBart: "Elsevier Science"
- GOKb: "Elsevier B.V." -- KBart: "Urban & Fischer; Elsevier" (no "Urban ..." in GOKb)
- GOKb: "Elsevier B.V." & "W.B. Saunders & Company" -- KBart: "W.B. Saunders/Elsevier"

Alone given these cases, we will at least meet the following issues:

- What about non-existent publishers?
- What about partly non-existent publishers?
- What about typing variations?
- How do we recognize multiple publishers? (varying separation characters)

**Comment by philboeselager** [comment]
@darupp Das Ticket scheint mir nicht weiter verfolgt zu werden, und es gibt auch keinen überzeugenden Lösungsansatz. Ich schlage daher, dass Du das Ticket schließt.

**Comment by darupp** [comment]
Ja, in der Tat. Wird geschlossen.
