### ISSUE TITLE
Drop invalid historyEvents from GOKb upload

### ISSUE THREAD

**Issue by philboeselager** [hbz/laser-ygor#160]

**Comment by philboeselager** [comment]
@hornmo While starting working on this, I'm realizing I need criteria. When is a history valid?

- Which are obligatory subfields?
- Which subfields need to have valid content?
- What is valid content for a subfield? (e. g. valid date formats...)

**Comment by hornmo** [comment]
@philboeselager As I alluded to back in #46 it would be best if information concerning history events would be gathered in a separate SRU call altogether (to retrieve all identifiers and title information). However, concerning your specific questions:

On the top-level of an event, no field _must_ be empty:
* The `date` _must_ be set (currently exactly in the format `yyyy-MM-dd' 'HH:mm:ss.SSS` – we may want to expand that on the other side).
* From/To are arrays with _at least_ one valid object (event participant):
  * A valid participant _must_ have a non-blank `title`.
  * A participant _should_ contain an array `identifiers` containing identifier objects:
    * An identifier object _must_ contain a non-blank `type`.
    * An identifier object _must_ contain a non-blank (and valid based on the type) `value`.

**Comment by philboeselager** [comment]
@hornmo Yes, the seperate SRU calls for linked titles will follow soon.

@darupp Please check the date format with hornmo, as we favoured for simpler formats recently. Everything is fine for me.

**Comment by philboeselager** [comment]
> On the top-level of an event, all fields _must_ contain information:
> * The `date` _must_ be set (currently exactly in the format `yyyy-MM-dd' 'HH:mm:ss.SSS` – we may want to expand that on the other side).
> * From/To are arrays with _at least_ one valid object (event participant):

@hornmo In case of `from` size and `to` size being > 1:

- What is the meaning (semantically)?
- Do `from` size and `to` size always have to be equal?
- Should we drop a `from` or `to` entry if it is invalid?
- In this case, should we also drop the according `to` or `from` entry of same index?

>   * A valid participant _must_ have a non-blank `title`.
>   * A participant _should_ contain an array `identifiers` containing identifier objects:

I would prefer to start with the identifier's minimum count being 1, in order to avoid mismatches. Would you be fine with that?

**Comment by hornmo** [comment]
> What is the meaning (semantically)?
    Do from size and to size always have to be equal?

Sorry, that was wrong on my part. Technically there may be multiple entries in `from` and `to`, but since our source (ZDB) splits those up as well each event must have exactly one participant on each side (so one in `from` and one in `to`). There may obviously be multiple events if a journal has an predecessor and an successor.

>  Should we drop a from or to entry if it is invalid?
    In this case, should we also drop the according to or from entry of same index?

If any participant is invalid or `from`/`to` contains no participant, the whole event should be dropped. This should not invalidate the title itself (but probably produce a warning).

> I would prefer to start with the identifier's minimum count being 1, in order to avoid mismatches.    Would you be fine with that?

I would strongly support this notion, as titles without any primary identifiers are basically worthless for matching.

**Comment by philboeselager** [comment]
Implemented and deployed on DEV.
