### ISSUE TITLE
Curatory group types

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#162]
There are first providers who are ingesting their titles itself. For data users, there should be an indication if a curatory group is of librarian or library provenience so that data users will know with whom they are communicating. 

Further, there is no in-system way to contact a curatory group, but only to contact it's members directly via its mail account. Would it be feasible to enter a contact mail address for the group itself? Should a member/user be flagged as responsible and his/her mail address be used? Is there another way?

I suggest:

  * Adding an attribute to the Curatory group *type* with refadatas 'commercial', 'academic'
  * Exporting this attribute with the curatory group via the APIs (where a curatory group is already given)
  * POSTBONED: Adding an attribute for a contact mail address

**Comment by philboeselager** [comment]
@darupp Sounds like a GOKb issue?!

**Comment by darupp** [comment]
@philboeselager Thanks, you're right. Closed.
