### ISSUE TITLE
Suggestion: stronger editing and deleting rights

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#163]
As open knowledge base, the goal of the GOKb is to work cooperatively on its content. To prevent edit wars, there is a weak permission system regarding curatory groups, so if you want to change packages that are not curated by your group, you get a warning message that can be overridden. 

As the prevention of edit wars for certain packages and as a mean of trust for data users who are getting back to a curatory group if the package is not correct, this warning message should be replaced with a stronger permission management.

Suggestions?

**Comment by darupp** [comment]
Should be easily changed when the "updating" button is removed.

**Comment by philboeselager** [comment]
@darupp Sounds like a GOKb issue?

**Comment by darupp** [comment]
Correct, closed
