### ISSUE TITLE
Title classes re-evaluation

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#164]
Renaming domain classes inheriting from TitleInstance to get closer to KBART standardisation:

  * Book --> Monograph
  * Journal --> Serial

Reworking of field *medium type* to show only acceptable values
  
  * Serial --> Journal, Proceedings, ...
  * Monograph --> Book, Audio, Video, ...

**Comment by philboeselager** [comment]
@darupp Please assign to me when this is more concrete.

**Comment by darupp** [comment]
Closed because of GOKb issue
