### ISSUE TITLE
KBART validation

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#168]
After uploading the KBART file, it should be
  * validated
  * if not valid: understandable error message
  * if valid: next step

### No UTF8 Encoding (See corresponding issue)
Error message EN: "The file is not encoded as UTF-8. Please convert the file or ask the provider for a file with the correct UTF-8 character set."
Error message DE: "Die Datei ist nicht als UTF-8 kodiert. Bitte konvertieren Sie die Datei zu UTF-8 oder fragen Sie den Anbieter nach einer korrekt kodierten Datei."

### Column Header is missing
Error message EN: "The columns with the headers {X, Y, Z} are missing. Please add the columns or ask the provider for a file with the missing columns. Note: The columns must be present, even though the values of each record are empty."
Error message DE: "Die Spalten mit den Überschriften {X, Y, Z} fehlen. Bitte fügen Sie diese Spalten hinzu oder fragen Sie den Anbieter nach einer Datei mit der fehlenden Spalten. Anmerkung: Die Spalten müssen in der Datei existieren, selbst wenn die Werte der einzelnen Einträge leer bleiben."

### Column Header is multiple
Error message EN: "The columns with the headers {X, Y, Z} occur multiple times. Please remove the redundant columns or ask the provider for a file without duplication"
Error message DE: "Die Spalten mit den Überschriften {X, Y, Z} kommen mehrfach vor. Bitte entfernen Sie die überzähligen Spalten oder fragen Sie den Anbieter nach einer Datei ohne Doubletten. "

### Error message footer
Under all error messages there should be a link to https://groups.niso.org/apps/group_public/download.php/16900/RP-9-2014_KBART.pdf with the link text:  
EN: "You can find the current KBART specification here."
DE: "Sie können die aktuelle KBART-Spezifikation hier finden."

**Comment by darupp** [comment]
@MiriKon , Could you please check understandability and the english translation?

**Comment by MiriKon** [comment]
@darupp : 

1. Maybe we should explain UTF-8 a bit more? --> "Die Datei ist nicht mit der **Zeichenkodierung** UTF-8 kodiert." // "The file is not encoded **in accordance with the character encoding** UTF-8." That way, people who have never heard of it before will at least have some notion of what UTF-8 is? Is there any link we could use to refer users to a page where the conversion to UTF-8 is explained (e.g. "This is how you convert your file to UTF-8")?

2. "Bitte fügen Sie die **entsprechenden** Spalten hinzu oder fragen Sie den Anbieter nach einer Datei mit de**n** fehlenden Spalten. Anmerkung: **Alle** **KBART-**Spalten müssen in der Datei existieren, selbst wenn die Werte der einzelnen Einträge leer bleiben." // "Please add the **missing** columns or ask the provider for a file **containing all** **appropriate** columns. Note: **All KBART**-columns must be **included in the file**, even **if** **some of** the values of each record **remain** empty."

3. "Die Spalten mit den Überschriften {X, Y, Z} kommen mehrfach **in der KBART-Datei** vor. Bitte entfernen Sie die überzähligen Spalten oder fragen Sie den Anbieter nach einer Datei ohne **Dubletten**. " // "The columns with the headers {X, Y, Z} **appear** multiple times. Please remove the redundant columns or ask the provider for a file without **any** duplication".

**Comment by darupp** [comment]
@MiriKon Thanks. Regarding a link to KBART conversion we should add this later, as there are multiple ways regarding the workplace environment of the user (Excel, LibreOffice Calc, Notepad++). We'll keep that in mind and will add a link if we have the time to write a tutorial.

@philboeselager You can take the messages including @MiriKon 's additions.

**Comment by philboeselager** [comment]
@darupp With the current implementation of org.apache.commons.csv.CSVParser, Only one multiplicated column is reported for each upload. As hopefully it is not very plausible that users try to upload KBART files with more than 1 multiplicated column, this should do no real harm.

Nonetheless, if this should prove being a problem, we still can change it.
