### ISSUE TITLE
Traffic lights status system

### ISSUE THREAD

**Issue by philboeselager** [hbz/laser-ygor#171]
DOD:

- A 3-state system is set up: "red", "yellow", "green".
- As soon as one field is red, the whole record is red.
- As soon as one field is yellow, the whole record is yellow, as long as there is no red field.
- (Hence, only records without red and yellow fields are green.)
- Yellow fields are called warnings.
- Red fields are called errors.
- There is a third, yellow, main frame in the statistics view, containing all yellow records.
- Green and yellow records will be send to the receiving data container (i. e. GOKb).
- Red records will not be send to a receiving data container.

**Comment by philboeselager** [comment]
@darupp Using a first version with yellow "warning" field lines in the _details_ view, it seems that there will be yellow fields in **every** record. Please see attachment. Therefore, the "overall green" status is very unlikely ever to be present in the statistics _overview_.

Hence, I would recomment not to introduce a third (yellow) box in the statistics _overview_, as it probably always would be empty. Instead, I would keep the yellow lines and keep the "non-red" records in the green _overview_ box.
![Ygor yellow lines](https://user-images.githubusercontent.com/10129448/72266436-a138e280-361e-11ea-914e-0fdc1e2e880b.png)

**Comment by philboeselager** [comment]
As agreed by now, we add a yellow record box and put all records in it that could not be matched in the ZDB API.

**Comment by darupp** [comment]
@philboeselager I agree, but not ZDB enriched titles should be highlighted in a yellow box.
So first (although unintuitive) solution:

  * yellow warning fields --> green box
  * No ZDB API call for serials --> yellow box

**Comment by hornmo** [comment]
The current implementation of the yellow fields does not seem to consider the `publicationType` of the title, which would eliminate around half of the highlighted rows in your example. Fields which are correctly empty in the context of the current title should not be highlighted. Also, it looks like somehow `ezbId` is highlighted although it has a valid value.

**Comment by philboeselager** [comment]
Waiting for clarification in #179 before solving the issues mentioned in hornmo's last comment.

**Comment by philboeselager** [comment]
Highliting in dependece of `publicationType` is implemented by https://github.com/hbz/laser-ygor/commit/9aa7e7ba56ae411ec6137d2c510b4b2fa79f2430.

**Comment by philboeselager** [comment]
Can be tested after being merged with https://github.com/hbz/laser-ygor/commit/9aa7e7ba56ae411ec6137d2c510b4b2fa79f2430.
