### ISSUE TITLE
Differentiation of serial and monograph via KBART publication_type

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#179]
* No selection of package type "journal" vs. "e-book"
  * Check for each record field "publication_type" if "serial" or "monograph"
  * Check if lines with other or no types exist - error message (KBART validation)
  * enrichment via ZDB or EZB only for "serial" type
  * field highlighting depends on publication type (see #171)

**Comment by philboeselager** [comment]
[Having removed both, the data type UI option and all its logic behind](https://github.com/hbz/laser-ygor/commit/4443583877f8d40198a04f5f99878ccc1bf11e12), I'm realizing that there is no such obligatory data field as `publication_type` ...strange enough.

Hence, I would suggest to change the goal / DoD to:

- Add third option for data types: "mixed"
- Add text input for column name of publication type that has to be set when "mixed" is chosen.

This replaces the first bullet point from above. The other 4 points remain the same: 

 for each record field "publication_type" if "serial" or "monograph"
- Check if lines with other or no types exist - error message (KBART validation)
- enrichment via ZDB or EZB only for "serial" type
- field highlighting depends on publication type (see #171)

@darupp Do you agree?

**Comment by philboeselager** [comment]
Thinking further... if there is no Kbart default field such as `publication_type`, we would also have to do one of the following:

- enable users to define the exact wording and spelling for a) serials / journals and b) monographs / books (add further text inputs)
- or pre-define this wording and render it in the UI, giving users the task to set the wording in their Kbart files

and show an error message on different wording occuring either way.

**Comment by darupp** [comment]
As in the KBART recommended practice 2014, _publication_type_ is not optional, but obligatory (See https://groups.niso.org/apps/group_public/download.php/16900/RP-9-2014_KBART.pdf Chapter 6.6.18). Therefore, I would suggest no manual selection, but known error message for missing column when _publication_type_ is missing.
