### ISSUE TITLE
NominalProvider wird durch die Plattform gefüllt

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#18]
Im Augenblick wird das JSON-Feld "nominalProvider" durch den Namen der Plattform gefüllt. Das ist falsch, hier müsste der Name des Providers (Organisation) stehen. 

Lösungsvorschlag: Ähnlich, wie in der YGOR-Oberfläche die Plattform per API-Call aus der GOKb geholt wird, können die Provider-Organisationen geholt werden.

**Comment by klodav** [comment]
Version 0.26

Eine Organisationsauswahl (_Content Provider_ oder _Publisher_) wird per Zugriff auf die GOKb-Datenbank erstellt. Die Funktionalität arbeitet analog zur Plattformauswahl.
