### ISSUE TITLE
Visualize API response resulting from GOKb upload

### ISSUE THREAD

**Issue by philboeselager** [hbz/laser-ygor#197]
We might want to visualize some feedback from a GOKb upload.

@darupp Please let me know, what we want do display and where / how to display it. Personally, I would favour a pop-up solution.

**Comment by darupp** [comment]
The info should be record specific.

@hornmo Is there a case matrix of different api responses in GOKb? At least there should be given:

- has there been a validation error? If yes, which field, which value and why?

**Comment by hornmo** [comment]
@darupp @philboeselager I have updated the [API documentation](https://github.com/openlibraryenvironment/gokb/wiki/Integration-APIs:-Telling-GOKb-about-new-or-corresponding-resources-and-local-identifiers) accordingly. 

There are still some improvements on the horizon, like adding the TIPP array index to the response and doing pre-validation for title crossref. Currently the errors are mostly represented in the form of a simple message string, this may be expanded to a more complex object representation if necessary.

**Comment by philboeselager** [comment]
The output of the message string in the modal was implemented in the last commit (adb91e7). In the current GOKb response, there is also a map keyed by `baddata` - but `baddata` contains **all** data of the record. Hence, it does not make sense to display the contents of it.

@hornmo Can you narrow down the content of `baddata` to the "real" bad data on the GOKb side?

**Comment by hornmo** [comment]
@philboeselager I'll have to look into that. The problem is, that there different types of errors that would have to be mapped individually (eg pre-validation errors or GORM ValidationExceptions). I would generally tend towards extending the `errors` object to always point out the offending field and value instead of just a message.

**Comment by philboeselager** [comment]
To be continued in #223. Closing.
