### ISSUE TITLE
ISSN mismatch between ZDB and KBART aborts processing

### ISSUE THREAD

**Issue by hornmo** [hbz/laser-ygor#198]
Testfile: https://github.com/openlibraryenvironment/gokb/files/3152744/EZB-HBZBE-01476_hbzKon_beck_2019_05_07.txt

Processing fails while querying ZDB with message: 
`ERROR processing.MultipleProcessingThread  - EISSN OnlineIdentifier : 2512-3688 already set to OnlineIdentifier : 2197-1609 for record`
`INFO  processing.MultipleProcessingThread  - Aborted MultipleProcessingThread run.`

When this happens, the user is immediately sent back to the initial processing view (_Select source file_) without any error message.

Since it is expected that KBART ISSNs may differ from those received from ZDB, this should not cause the whole run to be aborted. It may be useful to add the title to the list of warnings (and mentioning the replaced KBART ISSN in the validation message), but the value should generally be taken from ZDB.

**Comment by philboeselager** [comment]
@hornmo @darupp 

- There is also the field "all_issns" that is comprised in the downloads from the site. I assume it is designed to resolve these mismatches. Should we involve it in the solution to this issue?

**Comment by darupp** [comment]
@philboeselager No, as _all_issns_ is not a standard kbart field and only proprietary to ezb exports. I would, as @hornmo suggests, place this title in the warnings-section.

**Comment by philboeselager** [comment]
@darupp Logically, **if** `all_issns` exists and it contains the ISSN received from the ZDB API, it makes sense to "accept" the mismatch. This does not mean to build a solution that is dependent on the existence of `all_issns` of course.

But I'm going to flag it as a warning then, also if `all_issns` resolves the mismatch.
