### ISSUE TITLE
Leerzeichen im Dateinamen

### ISSUE THREAD

**Issue by HebisJC** [hbz/laser-ygor#2]
Zum Speichern des Packages und der Titles zieht Ygor zwecks Benennung den Dateinamen des hochgeladenen CSV heran. Enthält das hochgeladene CSV im Dateinamen jedoch Leerzeichen bricht die Benennung an dieser Stelle ab und man erhält eine Datei mit verkrüppeltem Namen und ohne Dateiendung. Gleiches gilt auch für die Debug-Datei und die Dateistruktur.

Unglücklicherweise erhält man dadurch für einen CSV-Upload insgesamt vier Exporte mit identischem Dateinamen.

**Comment by klodav** [comment]
Danke für den Hinweis. Leerzeichen werden jetzt durch Unterstriche ersetzt.

**Comment by klodav** [comment]
Version 0.13 ist deployed.
