### ISSUE TITLE
Package import per CrossReferencing API: Different import options

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#207]
Referencing GOKb issue https://github.com/openlibraryenvironment/gokb/issues/203

Checkbox on Step 2 under package title input field: "This package is an addition to an existing package. No existing TIPPs will be set to _retired_", de: "Bei dieser Titelliste handelt es sich um eine Ergänzung zu einem bestehenden Paket. Es werden keine bestehenden TIPPs auf _abgelaufen_ gesetzt"

This checkbox should only appear if the package title is found in the ES index so that the user has the information whether this package already exists or not. Additionaly, if the package is found, an icon should be shown after the package title input field. With mouseover "Package found - update package", "package not found - new package" (German: "Paket gefunden - Update" und "Paket nicht gefunden - neu anlegen!")

If the checkbox is set, in the "upload package" function the request parameter "addOnly" should be set to _true_. The default value (for request parameter and check box) is _false_.

**Comment by philboeselager** [comment]
As discussed with @darupp , the process could / should be as following:

Query name in GOKb: package exists?
- no --> create
- yes --> show dialog with 3 options
  - a) overwrite
  - b) complement
  - c) cancel

**Comment by philboeselager** [comment]
Done.
