### ISSUE TITLE
Matching von Tipp-URL mit Platform-URL des Packages

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#21]
Die Tipp-URL aus der KBART-Datei wird in Ygor noch mit der Plattform-URL gematcht, die aus der GOKb-Plattform ausgewählt wird. Das ist ein Relikt aus der Zeit, als die URL von Titeln aus der ZDB übernommen wurde. Diese Prüfung muss entfernt werden und die Tipp-URL normalisiert, aber ansonsten unverändert in das JSON geschrieben werden.

**Comment by philboeselager** [comment]
Solved in https://github.com/hbz/laser-ygor/commit/7249a56a42f84aa996091cfc9f48c59c9e4fd988 and deployed.
