### ISSUE TITLE
Credentials für GOKb müssen in YGOR abgefragt werden

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#22]

**Comment by philboeselager** [comment]
@darupp @klodav : Zur technischen Umsetzung: verstehe ich richtig, dass hier gewünscht ist, dass die GOKb-Credentials in einem PopUp eingegeben und anschließend als Parameter im API-Call an die GOKb gereicht werden - und zwar verschlüsselt?

**Comment by darupp** [comment]
Ja, genau

**Comment by philboeselager** [comment]
Done in 780558cdc08a98b91c4ad909f23d420136187463.

**Comment by darupp** [comment]
Das Passwort wird noch offen angezeigt, das Insertfeld müsste auf type="password" gesetzt werden.

**Comment by philboeselager** [comment]
> Das Passwort wird noch offen angezeigt, das Insertfeld müsste auf type="password" gesetzt werden.

Erledigt in https://github.com/hbz/laser-ygor/commit/4fadc9b8efda6c35131ac11875834f7d936e2ac1
