### ISSUE TITLE
Get paged results from backend

### ISSUE THREAD

**Issue by philboeselager** [hbz/laser-ygor#227]
The current implementation delivers all records from backend to frontend, having a serious performance bottle neck by doing this.

DOD: The delivery of resulting records is paged per category colour (red, yellow, green).

**Comment by darupp** [comment]
As most E-Book-Packages have >2000 records, this issue should be prioritized

Testfile added:

[https://app.zenhub.com/files/76962941/360e1c0a-7876-4973-9909-2f92df9d0c0d/download](https://app.zenhub.com/files/76962941/360e1c0a-7876-4973-9909-2f92df9d0c0d/download)

Additonal test files see #241
