### ISSUE TITLE
Abfrage von Platform und Publisher über ElasticSearch Index

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#23]
Der Use Case ist die Plattform- und Providerauswahl in YGOR. Im Augenblick greift Ygor  direkt auf die Datenbank der GOKb zu. Das birgt zwei Probleme: 

- Beide müssen auf dem selben Server liegen
- Security-Probleme

Das sollte geändert werden. Optionen wären
 
- Abgreifen des ES-Index (Was jetzt schon möglich ist)
- Eigenen API-Endpunkt entwickeln
- Bestehenden Endpunkt, z.B. für OpenRefine, nachnutzen.

**Comment by philboeselager** [comment]
@hornmo : der Index wird bisher ausschließlich von der GOKb befüllt, richtig? Daher ist die Frage, ob dies auch so bleiben soll und die Abfrage des ES-Index in eine GOKb-API-Funktion geschachtelt wird. Vorteile: 

- die Abfrage wird übersichtlicher und leichter zu parametrisieren
- der Index kann gekapselt werden (Datensicherheit)

Nachteil:

- höherer Umsetzungsaufwand

**Comment by berndoberknapp** [comment]
Ein GOKb-API wäre aus meiner Sicht eindeutig vorzuziehen. Welche Clients würden diese Informationen direkt im Index abfragen, sprich was ist der Use Case?

**Comment by darupp** [comment]
Der eigentliche Use Case ist tatsächlich die Plattform- und Publisherauswahl in YGOR. Im Augenblick greift Ygor direkt auf die Datenbank der GOKb zu - was kein Problem ist, solagne beide auf dem gleichen Server liegen (von der Security abgesehen). Am Montag haben wir uns über die verschiedenen Möglichkeiten unterhalten, Philipp und Moritz haben sich für die ES-Version ausgesprochen.

**Comment by berndoberknapp** [comment]
Ich nehme an, es ist Provider gemeint, nicht Publisher?

Platform und Publisher möchten wir für den Statistikserver zukünftig auch aus der GOKb übernehmen, daher wäre ein API auf jeden Fall sinnvoll, wenn das vorhandene API nicht das Gewünschte leistet.

**Comment by darupp** [comment]
Ja, Provider. Habe es geändert. Unter dem Aspekt erscheint eine API natürlich sinnvoll, nehmen wir dann so als Vorschlag in die GOKb mit.

**Comment by philboeselager** [comment]
@hornmo Gibt es schon einen Branch auf [github/hbz](https://github.com/hbz/gokb-phase1), in dem eine API implementiert ist?

**Comment by hornmo** [comment]
Ist seit dem letzten Pull-Request auf v7_dev_integration vorhanden:

http://phaeton.hbz-nrw.de/gokb/api/find?label=Springer&componentType=Org

**Comment by philboeselager** [comment]
Deployed mit https://github.com/hbz/laser-ygor/commit/f48c829bf2a2fe14b1d487f5aab2f9cd804a0c11 .
