### ISSUE TITLE
Package JSON: Namespace mismatch

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#231]
Tested with YGOR 0.88 on phaetondev.

The package JSON doesn't map correctly printIdentifiers and onlineIdentifiers. So wrong identifiers are inserted into GOKb.

```
 "title" : {
      "identifiers" : [ {
        "type" : "onlineIdentifier",
        "value" : "2042-8332"
      }, {
        "type" : "printIdentifier",
        "value" : "1753-0180"
      }, {
        "value" : "amhld",
        "type" : "emerald"
      }, {
        "type" : "zdb",
        "value" : "2625869-9"
      } ],
      "name" : "Advances in mental health and learning disabilities",
      "type" : "Serial"
    },
```
[https://app.zenhub.com/files/76962941/2e7d417c-c3ed-464d-b50a-3c68ab8e1858/download](https://app.zenhub.com/files/76962941/2e7d417c-c3ed-464d-b50a-3c68ab8e1858/download)

**Comment by philboeselager** [comment]
@darupp Please specify the correct behaviour. I'm guessing you mean that `onlineIdentifier` should be `eissn` and `printIdentifier` should be `issn` ?

**Comment by darupp** [comment]
Yes, but only for journals. I didn't specify it because it already worked and I guessed that it would be only a bug.

**Comment by darupp** [comment]
Specification: 

# publication_type _monograph_

- print_identifier -> pisbn
- online_identifier -> isbn

# publication_type _serial

- print_identifier -> issn
- online_identifier -> eissn

Please check the code if there are discrepancies from this rules, because, as I said, this worked fine since the very first versions of ygor.

**Comment by darupp** [comment]
Reopened
YGOR 0.89 on dev

There are still errors regarding the namespaces. The `online_identifier` is matched to `eisbn`. This namespace does not exist. For monograph namespaces see last comment.
