### ISSUE TITLE
Wrong date parsing in Package JSON

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#232]
Tested on YGOR 0.88, phaeton-dev

Regarding title "Advances in mental health and learning disabilities"

Although in the KBART file there is a clearly parseable date for date_last_issue_online of 2010-03-15, in the package JSON the coverage is endDate is set to 2003.

Random samples suggests that every date is parsed wrong. In most cases there is only a year given - and often not the correct year.

[https://app.zenhub.com/files/76962941/26c9d34c-f9d6-4f18-ae60-ad63be1db26c/download](https://app.zenhub.com/files/76962941/26c9d34c-f9d6-4f18-ae60-ad63be1db26c/download)

**Comment by philboeselager** [comment]
Fixed while working on #224. Closing.
