### ISSUE TITLE
Thieme eRef Lehrbücher mit Ygor dev

### ISSUE THREAD

**Issue by MiriKon** [hbz/laser-ygor#236]
Ich habe das Einspielen der eRef Ebooks mal mit dem neuen Ygor auf dev getestet. Folgendes ist aufgefallen:

- Beim Hochladen einer KBART-Datei, die nicht alle Spalten enthält, wird die Datei nicht genommen. Es kommt zwar eine Fehlermeldung und alle fehlenden Spalten werden aufgezählt (s. Screenshot), aber das ist natürlich sehr unpraktisch. Es sollte auch möglich sein eine Datei hochzuladen, die nur ausgewählte KBART-Spalten aufweist
![Ygor1](https://user-images.githubusercontent.com/45172978/77311995-7398a580-6d01-11ea-9158-7173adbde2a2.jpg)

- (da es sich um Ebooks handelt, habe ich übrigens keine ZDB/EZB Anreicherung angehakt) bei der Rückmeldung in Ygor sind alle Einträge als ungültig befunden worden (s. Screenshot), was ziemlich schräg bei Ebooks ist, weil die ja nicht angereichert werden
![Ygor2](https://user-images.githubusercontent.com/45172978/77312114-acd11580-6d01-11ea-8f0c-790bc83c841f.jpg)
![Ygor3](https://user-images.githubusercontent.com/45172978/77312118-ae9ad900-6d01-11ea-8310-35903ba8c5ca.jpg)
![Ygor4](https://user-images.githubusercontent.com/45172978/77312120-afcc0600-6d01-11ea-9cbd-d770fa175168.jpg)

Die Testdatei ist diese hier gewesen:
[Thieme_Ebooks_eRef_Lehrbuecher_19_03_2020_test_23_03_2020.txt](https://github.com/hbz/laser-ygor/files/4368985/Thieme_Ebooks_eRef_Lehrbuecher_19_03_2020_test_23_03_2020.txt)

**Comment by darupp** [comment]
zu 1) "Es sollte auch möglich sein eine Datei hochzuladen, die nur ausgewählte KBART-Spalten aufweist" - Das ist schwer zu spezifizieren, wie wir gesehen haben. Daher gilt zunächst: Alle Spalten müssen als Header existieren. Sonst passiert leicht Fehler Nr. 2). Hierzu schiebe ich das Ticket in die Icebox.

zu 2) Die Spalte `publication_type` muss mit "monograph" oder "serial" belegt sein, weil sonst die GOKb nicht wissen kann, was für ein Titeltyp eingespielt wird. Ygor fängt das korrekt auf. Hier muss der Anbieter gemäß dem KBART-Standard nachbessern.

**Comment by philboeselager** [comment]
> zu 1) "Es sollte auch möglich sein eine Datei hochzuladen, die nur ausgewählte KBART-Spalten aufweist" - Das ist schwer zu spezifizieren, wie wir gesehen haben. Daher gilt zunächst: Alle Spalten müssen als Header existieren. Sonst passiert leicht Fehler Nr. 2). Hierzu schiebe ich das Ticket in die Icebox.

@darupp Was ist an dieser Stelle Ygor-seitig zu verändern? Also was ist das Ziel-Verhalten?

**Comment by darupp** [comment]
Es ist ja gerade deswegen in der Icebox, da das schwer zu definieren ist. Die Zahl der Pflichtspalten hängt ab vom publication_type, der aber erst in späteren Schritten ausgewertet wird. Für diese YGOR-Version daher bitte zunächst ignorieren.

**Comment by philboeselager** [comment]
Die Zahl der obligatorischen Spalten wurde zwischenzeitlich minimiert.
