### ISSUE TITLE
Manual deleting of field not possible

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#237]
Happens in the title edit screen `/ygor/statistic/edit/XXX`

If you delete a field manually by klicking in it and using _Del_ or _Backspace_, you have HTML artifacts after saving with _Enter_. 

Example: `publisher_name` "Emerald" becomes `<br>` after editing. Entering a blank doesn't work also, because the field content becomes `&nbsp;`

This could prevent validation if there is a field validation.

**Comment by philboeselager** [comment]
@darupp Which browser do you use? Works fine on Chromium and presumably Chrome.

**Comment by darupp** [comment]
Firefox 74.0 (Windows 10) and
Firefox, unknown version (Linux Mint 19)

**Comment by philboeselager** [comment]
Confirmed for Firefox 74.0.
