### ISSUE TITLE
Change of ZDB subtitle processing when KBART publication_title is used

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#238]
The prioritiy of the `publicationTitle` will be reversed - if a KBART `publication_title` is given, this one is used as main title. 

The ZDB title `021A:a` should be inserted into the title JSON as Alternate Title. Only this alternate title should be concatenated / enriched via via ZDB Subtitle fields `021C:l` `021C:a` `021C:r`, not the publicationTitle.

**Comment by philboeselager** [comment]
@darupp Following the [GOKb API documentation](https://github.com/openlibraryenvironment/gokb/wiki/Integration-APIs:-Telling-GOKb-about-new-or-corresponding-resources-and-local-identifiers), there is no field like `alternateTitle` being processed in the GOKb. Should we send this field anyway? (It has no effect then.)

Alternatively, we can change the priority for `title` in such a way that we simply take the KBart value as prio 1 and leave the rest as it is prioritized by now.

**Comment by darupp** [comment]
For now, I think your alternative is the best solution. I think I have changed the priority order, but we have to ensure that  `021C:l`, `021C:a` and `021C:r` are not concatenated after the KBART `publication_title`

@hornmo Do you think we could enhance the API to accept `alternateTitle`?

**Comment by hornmo** [comment]
This is an oversight in the API docs. For packages as well as titles the API does process alternative names contained as Strings in an array of  `variantNames`.

**Comment by hornmo** [comment]
I have updated the docs accordingly, including the parameter features `àddOnly` & `async`.

**Comment by darupp** [comment]
Temporary change to enforce KBART title without ramification:

https://github.com/hbz/laser-ygor/blob/323171b1975f0f0539dce4b89c36d9b04b652b64/src/groovy/de/hbznrw/ygor/export/GokbExporter.groovy#L212

This should be enhanced: 
  * `publicationTitle` should come as it is now, that means as as KBART `publication_title` without ramification. This should also be the YGOR display title
  * ZDB Title with ramification should be inserted als `variantName`.

**Comment by philboeselager** [comment]
This issue is stale and an updated process meanwhile has been implemented.
