### ISSUE TITLE
Normalization of publication_type

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#247]
The field `publication_type` should be normalized. 

Accepted Input
`monograph`, `Monograph`, `serial`, `Serial`

Output
`serial`, `monograph`

Issue on hold until the GOKb can handle small case values.

**Comment by philboeselager** [comment]
@darupp What is the status of this issue?

**Comment by darupp** [comment]
Please ask @hornmo whether GOKb can now handle small case values.

**Comment by darupp** [comment]
Right now, the GOKb only accepts upper case Inputs as opposed to KBART standard.

**Comment by philboeselager** [comment]
Will be switched to lower-case after this is fully implemented on GOKb-side. @hornmo will give a note on this.

**Comment by philboeselager** [comment]
@hornmo Is this implemented in the current GOKb head?
