### ISSUE TITLE
Support GOKb package integration addOnly param

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#248]
In GOKb 8.5.3 a new `addOnly` param for package integration has been added. 

> If TIPPs of the existing package are not present in the update, their status will be set to `Retired` by default. This > behavior can be overridden by supplying the request parameter `addOnly=true`.

https://github.com/openlibraryenvironment/gokb/wiki/Integration-APIs%3A-Telling-GOKb-about-new-or-corresponding-resources-and-local-identifiers

This parameter should be asked for in YGOR in step "define package data" as Checkbox. 

Designator: "Add titles only" (DE: "Titel nur hinzufügen") with Questionmark-Icon and Mouseover:

EN: "If the package exists in the GOKb and the package titles (TIPPs) are not present in the KBART file, their status will be set to `Retired` by default. If you check this field, no TIPPs of the existing package will be set to `Retired`"

DE: "Wenn das Paket schon in der GOKb existiert und vorhandene Pakettitel (TIPPs) nicht in der KBART-Datei vorhanden sind, werden diese in der GOKb auf `Abgelaufen` gesetzt. Wenn Sie diese Option anwählen, wird kein Pakettitel im existierenden GOKb-Paket auf `Abgelaufen` gesetzt."

Subsequently, the parameter should be set in the package API call.

**Comment by MiriKon** [comment]
Eventuell eher:

DE: "Spielen Sie eine KBART-Datei mit ausschließlich neuen Titeln ein, die einem bereits existierenden Titelbestand eines GOKb-Pakets hinzugefügt werden. Bereits im GOKb-Paket eingespielte Titel bleiben von der Aktualisierung unberührt und nicht auf ABGELAUFEN gestellt, wenn diese nicht in der aktuellen KBART-Datei aufgeführt werden."

EN: "Use a KBART file exclusively consisting of new titles for the upload. These new titles will be added to the chosen GOKb package. The existing titles within the GOKb package will remain unchanged by the newly imported titles and will not be set to RETIRED if they are not listed in the newest KBART file."

Spiegelt das die Funktion wieder?

**Comment by darupp** [comment]
Ja, das ist gut, ich würde noch voran setzen: "Wenn Sie diese Option wählen, spielen Sie eine KBART-Datei ein..." bzw. "By selecting this option, you can use a KBART file ..."

**Comment by philboeselager** [comment]
@darupp Where in the UI should the checkbox be added?

**Comment by darupp** [comment]
No, this parameter should be asked for in YGOR in step "define package data" as Checkbox, where you can enter the package name.

**Comment by croqueGrec09** [comment]
Tested with Thieme: eRef Lehrbücher and the KBART file Thieme eRef Lehrbuecher

Test results:
Selected package has been updated with 303 new titles! The already existing title is still current!

Improvements suggested:
- Feedback whether the selected package exists would be useful, maybe restriction / warning if a non-existing package name has been given
- Feedback of how many new tipps have been added to package and how many retired
