### ISSUE TITLE
Aussagekräftige Fehlermeldung bei falschen Headern der KBART-Datei

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#25]
Zur Zeit kommt als Fehlermeldung bei falschen KBART-Headern ein Stacktrace mit IllegalArgumentException. Hier sollte eine aussagekräftige Fehlermeldung stehen, die den fehlerhaften Header anzeigt.

**Comment by philboeselager** [comment]
In diesem Zusammenhang sollten alle fehlenden Spalten auf einmal angezeigt werden.

**Comment by philboeselager** [comment]
Merged in 6b8351dabc737d43be6928d62d2b14b62433da9d and deployed.
