### ISSUE TITLE
Package can not be processed

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#259]
https://phaeton-dev.hbz-nrw.de/ygor/statistic/show?originHash=7352a4a0c8a4a8958aaf9e62b9e2d5ac&resultHash=667c8ad981ab17d2ffa503c9aa18e0be

Version 0.90
Basierend auf Grails 2.5.6
Angeschlossene GOKb-Instanz: https://phaeton-qa.hbz-nrw.de/gokb/
Build: 18.05.2020 11:05
Branch: origin/master 

Browser: Firefox 76.0.1 

```
An error has occurred
Error processing GroovyPageView: Cannot execute null+null
```

Settings:
KBART-File: Springer_Global_Springer_Book_Archive_-_Wirtschaftswissenschaften_2020-04-03.txt (given)

 Titel: Springer WiWi Archiv Test 20200518
Paketsigel (ISIL) der ZDB: <empty>
Interner Paket-Identifikator: <empty>

GOKb Plattform: SpringerLink
GOKb Provider: SpringerNature
Namensraum für proprietären Titel-Identifkator des Providers (title_id): doi
GOKb Curatory Group: hbz

Schnittstellen: KBART (no ZDB, no EZB)

Error occurs after the Enrichment Process reaches 100%

![ygor_error.png](https://images.zenhubusercontent.com/5cade8259e9eeb5df9b0faac/9ca6f39a-160c-4b26-a4f7-56a1e5f00aae)

**Comment by philboeselager** [comment]
Fixed in 292fec99d78c067271b19631a3f3c645081c6a4e and deployed on phaeton-dev.
