### ISSUE TITLE
Fehlermeldungen in YGOR sollen Review Requests in GOKb erzeugen

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#26]
Die Nachbearbeitung eines eingespielten Pakets sollte an einer Stelle erfolgen. Sinnvoll ist es daher, für Statusmeldungen bei YGOR entsprechende Review Requests in der GOKb zu erzeugen. 

Das kann nur die Fehlermeldungen bei YGOR betreffen, bei denen eine Nachbearbeitung möglich ist, d.h. zu denen tatsächlich ein Review Request in der GOKb sinnvoll angelegt werden kann. Fehler, die dazu führen, dass keine Daten an die GOKb geschickt werden, sind nicht sinnvoll als Review Request abzubilden.

Evtl. kann auf der GOKb-Seite dann die Schnittstelle so erweitert werden, dass YGOR-Statusmeldungen mitgeschickt werden und so Review Requests erzeugt werden können. 

Zu prüfen ist also: 

- Kann eine Statusmeldung prinzipiell einen Review Request in der GOKb erzeugen, weil ein entsprechendes Objekt gesendet wird?
- Wird jetzt schon ein Review Request aufgrund einer bestimmten YGOR-Statusmeldung erzeugt?
- Wie soll mit den Statusmeldungen umgegangen werden, die keinen Review Request erzeugen?

**Comment by philboeselager** [comment]
Wird geschlossen, weil sehr weitgefasst und unklar, und veraltet. Im Falle des bestehenden Interesses bitte neu formulieren.
