### ISSUE TITLE
Resend to start at 30 % without explanation

### ISSUE THREAD

**Issue by croqueGrec09** [hbz/laser-ygor#261]
When a package enrichment took place with errors, every following enrichment breaks at 30 % and sends back to the starting page without any explanation.

**Comment by philboeselager** [comment]
Confirmed. This occurs "out of nothing". Ygor may have been running seemlessly before.
The log message is:

    2020-05-19 14:43:36,499 [Thread-71] ERROR processing.MultipleProcessingThread  - No such property: IntegrationStatus for class: ygor.integrators.ZdbIntegrationService

**Comment by philboeselager** [comment]
Hopefully fixed within the last commit. There is no chance to test this, as the error occurs by chance and very rarely. In case of re-occuring, please re-open this issue.

**Comment by croqueGrec09** [comment]
Could not be reproduced so far. Is under observation.
