### ISSUE TITLE
AVA URL invalid in Ygor

### ISSUE THREAD

**Issue by MiriKon** [hbz/laser-ygor#263]
It would be very important that Ygor also recognizes URLs that may look a bit "unusual", e.g. the URLs for AVA (s. attached KBART file)
[hbz.ava.watch_26 May 2020_kbart.txt](https://github.com/hbz/laser-ygor/files/4722080/hbz.ava.watch_26.May.2020_kbart.txt)

**Comment by philboeselager** [comment]
Fixed in https://github.com/hbz/laser-ygor/commit/40eb8e88a65d9a1eb57273676babfd2ed90a4e0a.
