### ISSUE TITLE
Fortschrittbalken "Package zur GOKb senden"

### ISSUE THREAD

**Issue by MiriKon** [hbz/laser-ygor#265]
Ich hatte in Ygor Prod (https://gokb.org/ygor/) sowohl mit der AVA wie auch der OECD iLibrary KBART Daten via Ygor in die GOKb (org) eingespielt und beide Male hatte der Fortschrittbalke bei 0% gestoppt, komischerweise ist das Package aber trotzdem in die GOKb gekommen (bei AVA korrekt mit allen Titeln, bei OECD nicht, hier erstelle ich dann ein entsprechendes GOKb Ticket). 

D.h. das Problem ist, dass man nun gar kein Feedback erhält, ob das Package überhaupt an die GOKb gesendet wurde und als Nutzer denkt man, dass ein Fehler vorliegt.

[hbz.ava.watch_26 May 2020_kbart.txt](https://github.com/hbz/laser-ygor/files/4831281/hbz.ava.watch_26.May.2020_kbart.txt)
[OECD_ilibrary_Journals_August2019.txt](https://github.com/hbz/laser-ygor/files/4831290/OECD_ilibrary_Journals_August2019.txt)

**Comment by croqueGrec09** [comment]
Das Eigenartige ist, dass unter Ygor-DEV (v0.92) der Fortschrittsbalken durchaus zuverlässig funktionierte, ja sogar bis 101 % ging!

**Comment by philboeselager** [comment]
Das verstehe ich auch noch nicht. Auf meiner lokalen Umgebung läuft der Fortschrittsbalken ebenfalls zuverlässig. Ich werde hornmo fragen, ob er eine Idee hat, warum das auf Produktion weniger rund läuft.

Ich habe die vage Vermutung, dass es am Timing der beteiligten Prozesse liegt.

**Comment by hornmo** [comment]
Das liegt an einem neuen Konfigurationswert für den Fortschritt, der auf gokb.org noch fehlt. Für die Korrektur muss die Ygor-Instanz einmal neu deployt werden. Ich kann leider nicht überprüfen, ob gerade aktive Sessions in Ygor laufen, da durch die Monit-Calls durchgängig eine Menge an offenen Sessions existieren. Daher würde ich das wahrscheinlich sicherheitshalber heute abend machen.

**Comment by philboeselager** [comment]
Fixed.
