### ISSUE TITLE
Datenanreicherung - Ygor Feedback

### ISSUE THREAD

**Issue by MiriKon** [hbz/laser-ygor#266]
In Ygor Prod (https://gokb.org/ygor/) habe ich die 2019er KBART der OECD iLibrary eingespielt - ohne ZDB-Anreicherung. Beim Feedback nach dem Prozessieren in Ygor werden mir als Feedback dann zu prüfende Einträge angezeigt, wo ich mal draufgeklickt habe. Da fällt mir auf, dass die Rückmeldung für den fehlenden ZDB Abgleich rot markiert ist (S. Screenshot), was mich in dem Moment irritiert hat, weil rot eigentlich für "hat nicht geklappt" steht. Es wäre sehr hilfreich, wenn das Feedback hier auch in orange käme - generell sollte sich das dann bei den "zu prüfenden Einträgen" immer so durchziehen, dass hier in der Detail-Ansicht keine roten Feedback-Markierungen kommen.
![OECD_Ygor_Feedback](https://user-images.githubusercontent.com/45172978/85725367-55be5080-b6f5-11ea-8573-c8a946c8145e.jpg)

**Comment by philboeselager** [comment]
Macht Sinn. Bitte lass uns die 4 möglichen Fälle kurz definieren, @MiriKon :

A) roter Record (also mit einem Fehler, der Einspielen verhindert), Option "ZDB-Anreicherung" beim Einspielvorgang gewählt --> Farbe rot
B) roter Record, Option "ZDB-Anreicherung" NICHT gewählt --> Farbe ?
C) gelber Record (also mit unkritischem Fehler), Option "ZDB-Anreicherung" gewählt --> Farbe ?
D) gelber Record,Option  "ZDB-Anreicherung" NICHT gewählt --> Farbe gelb

**Comment by MiriKon** [comment]
Ich würde definieren:

Solange man mit der ZDB anreichert und es in dem Einspielprozess dann zu einem roten Record für einen Titel kommt, der ultimativ etwas mit dem ZDB-Abgleich zu tun hat, sollte die Fehlermeldung für das entsprechende Feld auch rot sein.

Solange man nicht die Option annimmt mit der ZDB anzureichern, sollte die Fehlermeldung bei einem Titel immer gelb sein, da es in der Situation ja nicht kritisch ist, dass etwas beim ZDB-Abgleich aufgefallen ist, es ist also eine reine Info. D.h. solange man nicht anreichern will, ist alles was mit der ZDB an Feldern zu tun hat auch unkritisch und kann gelb erscheinen. 

Perspektivisch sollten wir noch im Kopf behalten, dass bei diesem Thema natürlich auch eine direkte Rückmeldung der "angemeckerten" Titel an die ZDB geben sollte/könnte. Also eine Art Benachrichtigung an die ZDB, dass bestimmte Titel in der ZDB auf Aktualität/Vollständigkeit geprüft werden sollten. Aber als ersten Schritt würde ich es wie oben definieren. Hilft das?

**Comment by philboeselager** [comment]
OK, das kann man ausprobieren. Es ist etwas aufwändiger, als es scheint. Denn um zu wissen, ob ein Fehler durch die ZDB-Anreicherung entstanden ist, muss zu jedem Feld die Information hinterlegt werden, durch welche Quelle die Anreicherung erfolgt **ist**. Bislang wird jedoch nur für jedes Feld definiert, in welcher Reihenfolge die Anreicherungsquelle gewählt werden **soll**.

Das lässt sich mit etwas Aufwand nach-implementieren, dürfte jedoch auch zu einem gewissen Performance-Verlust führen, da diese Information immer generiert und transportiert werden muss (Erhöhung des Traffics und des Speicherbedarfs).

Fachlich ist das sicherlich die besser Lösung. @MiriKon Bitte entscheide, ob der Unterschied so erheblich ist, dass eine deutlich längere Implementierung sowie ein Performance-Verlust dadurch in Kauf genommen werden sollen.

Die einfache Lösung wäre, entsprechend der obigen Auflistung und Deiner Antwort:

A) --> rot
B) --> gelb
C) --> gelb
D) --> gelb

**Comment by MiriKon** [comment]
Da die Verbesserung zurzeit nur "nice to have" ist und wenn es sonst wieder zu längeren Wartezeiten beim Hochspielen kommt, würde ich deinen Vorschlag für die momentan einfachere Lösung nehmen. Ggf. müssten wir dann künftig schauen, inwieweit hier nochmal was "gemacht" werden muss, aber so sollte es dann erst einmal gelöst sein und es schaue es mir dann beim Einspielen mal an, sobald es gebastelt wurde.

**Comment by philboeselager** [comment]
@MiriKon Auf DEV deployed.

**Comment by philboeselager** [comment]
@MiriKon Auf QA deployed.

**Comment by philboeselager** [comment]
@MiriKon Auf PROD deployed.
