### ISSUE TITLE
KBART-Spalten Ygor

### ISSUE THREAD

**Issue by MiriKon** [hbz/laser-ygor#267]
Wenn ich neue KBART-Dateien von den verschiedenen Anbietern einspiele, fällt mir öfter auf, dass Ygor (https://gokb.org/ygor) immer noch meckert, wenn nicht bestimmte Spalten in der KBART mitgeliefert sind. Allerdings sind je nach Produkt des Anbieters auch nicht immer unbedingt all diese Spalten notwendig und es ist sehr mühselig, die dann erst noch in die Datei zu basteln. 

Deshalb sollte für Ygor nur wichtig sein, dass mindestens der publication_title und die title_url enthalten sind. 

Solange die befüllten Spalten KBART-konform sind, sollte Ygor danach dann nicht meckern, wenn weitere Spalten nicht aufgeführt sind (die Reihenfolge, in der die Spalten in der KBART aufgeführt sind, sollte zudem auch egal sein, aber das scheint mittlerweile gegeben).

**Comment by croqueGrec09** [comment]
Hierzu sei angemerkt, dass der alte Hintergrund, nämlich dass nur EBooks, Journals und Datenbanken eingespielt werden konnten, dafür verantwortlich ist, dass online_identifier und print_identifier Pflicht sind.
Hier sei auch hinzugefügt, dass bei Tests mit Ygor-DEV (v0.92) das Fehlen eines online_identifiers bei den Titel nicht angemerkt wurde bei der beigefügten AVA-Liste.
[hbz.ava.watch_26 May 2020_kbart.txt](https://github.com/hbz/laser-ygor/files/4831624/hbz.ava.watch_26.May.2020_kbart.txt)

**Comment by MiriKon** [comment]
Das mit den Medientypen stimmt - wird aber auch grundsätzlich aufgeweicht werden müssen, da diese starke Wahl nach Monograph und Serial nicht sinnvoll ist, wenn man all die "Zwitter" an Medientypen gibt, die dann weder noch sind. Das nehme ich aber auch als großes Ticket in der GOKb auf.

**Comment by philboeselager** [comment]
> Deshalb sollte für Ygor nur wichtig sein, dass mindestens der publication_title und die title_url enthalten sind.

Das muss in einem größeren Kontext betrachtet werden.

- Ygor verarbeitet Dateien, die den Anforderungen des KBart-Format's genügen.
- Die Spezifikation des KBart-Format's sieht vor:

    "Because recipients of metadata files will be expecting to receive all files in a matching format, every field
should appear in the order given below, even if the content provider is unable to provide any information
or no information is appropriate for a specific field." (http://travesia.mcu.es/portalnb/jspui/bitstream/10421/8966/1/rp-9-2014_KBART.pdf)

Die Reklamierungen durch Ygor beziehen sich auf die Felder, die in der KBart-Spezifikation als "mandatory" bezeichnet werden, wobei in der Spezifikation auch immer wieder das Wort "should" verwendet wird.

Je weniger Felder von Ygor explizit verlangt werden, desto mehr Hinweis an die Benutzenden auf das KBart-Format muss letztlich von fachlicher Seite erfolgen. Natürlich liegt all dem der Gedanke zugrunde, dass der Umfang der Information ihre Gesamtgüte verbessert. Will sagen: Anbieter sollen durch das explizite Verlangen obligatorischer KBart-Felder dazu gebracht werden, ihre Daten zu verbessern.

Einen Titel lediglich anhand seiner URL zu identifizieren, ist mit einem Risiko behaftet. Denn nicht allen Anbietern wird klar sein, dass sich unter diesen Umständen Titel-URLs niemals ändern dürfen. Deshalb sollte aus Qualitäts-Aspekten immer mindestens ein weitere Identifier aus `print_identifier`, `online_identifier`, `title_id`, `doi_identifier` oder die ZDB-ID gegeben sein.

Der `publication_type` muss angegeben werden, da Ygor sonst nicht weiß, wie mit der jeweiligen Zeile zu verfahren ist.

Auf andere Felder kann ohne allzu enorme Bauchschmerzen verzichtet werden, wie z. B.:

- date_first_issue_online
- num_first_vol_online
- num_first_issue_online
- date_last_issue_online
- num_last_vol_online
- num_last_issue_online
- first_author
- embargo_info
- coverage_depth
- notes
- publisher_name
- date_monograph_published_print
- date_monograph_published_online
- monograph_volume
- monograph_edition
- first_editor
- parent_publication_title_id
- preceding_publication_title_id
- access_type

Wäre diese Lösung praktikabel genug, @MiriKon ?

**Comment by MiriKon** [comment]
Das verstehe ich - ich werde für das "Gesamtproblem" auch noch GOKb-seitig ein Ticket aufsetzen. Könnten die Spalten, die du als "machbar ohne Bauchschmerzen" auflistest, dann relativ schnell als Must-Have bei Ygor raus oder wäre das sehr viel Aufwand? Dann würde ich sagen, dass du die dann schon mal rausnimmst und wir an der andere Sache dran sind, da das ja die GOKb allgemein auch betrifft.

**Comment by philboeselager** [comment]
@MiriKon Auf DEV deployed.

**Comment by philboeselager** [comment]
@MiriKon Auf QA deployed.

**Comment by philboeselager** [comment]
@MiriKon Auf PROD deployed.
