### ISSUE TITLE
Feedback Ygor

### ISSUE THREAD

**Issue by MiriKon** [hbz/laser-ygor#268]
Generell wäre es super, wenn man in Ygor immer schon direkt die Anzahl der jeweils gültigen KBART-Einträge, zu prüfenden oder fehlerhaften Einträgen sehen könnte, so dass man auch weiß, ob alle Titel aus der Datei prozessiert wurden in Ygor. Ich habe mal ein Beispiel im Anhang: hier wäre es schön die Anzahl direkt in der farbigen Feedback-Leiste zu sehen.
![Ygor_Feedback](https://user-images.githubusercontent.com/45172978/85832995-50164880-b791-11ea-879e-a3ff45db76e5.jpg)

**Comment by philboeselager** [comment]
@MiriKon Auf DEV deployed.

**Comment by philboeselager** [comment]
@MiriKon Auf QA deployed.

**Comment by philboeselager** [comment]
@MiriKon Auf PROD deployed.
