### ISSUE TITLE
Datei verarbeiten: Fortschrittsbalke stockt bei 100%

### ISSUE THREAD

**Issue by MiriKon** [hbz/laser-ygor#269]
Ich habe gerade die KBART-Datei des Anbieters IBISWorld einspielen wollen in Ygor Prod (https://gokb.org/ygor/enrichment), allerdings stockt der Fortschrittsbalke beim Prozessieren seit ca. 5 Minuten bei 100%. Ich denke, das könnte daran liegen, dass es an die 8000 Titel sind, die sich in der KBART-Datei befinden, allerdings finde ich dann die Angabe der 100% etwas fragwürdig, weil das Prozessieren scheinbar noch andauert und es dann ja noch keine 100% sein können. Das wäre gut, wenn das umgestellt würde, so dass es bei 100% dann auch "durch" ist und nicht noch hängt. 

Die Datei von IBISWorld hänge ich hier einmal ein.
[KBART_test1_ibisworld.txt](https://github.com/hbz/laser-ygor/files/4857935/KBART_test1_ibisworld.txt)

**Comment by philboeselager** [comment]
Auf DEV und QA deployed.
