### ISSUE TITLE
Pakettitel-Feld in Ygor

### ISSUE THREAD

**Issue by MiriKon** [hbz/laser-ygor#270]
Bei Ygor (https://gokb.org/ygor/enrichment/process) taucht, sobald man die Datei hochgeladen hat, immer noch im Feld "Titel" ein Beispiel auf, wie man den Paket-Titel aufnehmen soll. Da diese Konvention nicht mehr genutzt wird, sollte hier kein Beispiel mehr erscheinen, da der Paketname frei vergeben werden kann. 
![Ygor_Titelfeld](https://user-images.githubusercontent.com/45172978/86252015-f065d600-bbb2-11ea-8822-d885a520d715.jpg)

**Comment by philboeselager** [comment]
Auf DEV und QA deployed.
