### ISSUE TITLE
AVA KBART-Einspielung

### ISSUE THREAD

**Issue by MiriKon** [hbz/laser-ygor#279]
Beim Einspielen der neusten AVA-KBART in Ygor (https://gokb.org/ygor) sind die 500 Titel korrekt prozessiert worden und als intakt gemeldet beim Senden der Titel an die GOKb. Beim Senden des Package an die GOKb (überhaupt notwendig wenn das Paket schon besteht?) kam allerdings eine Fehlermeldung, so dass das Paket und der Bestand nicht aktualisiert wurden (weiterhin nur 385 Titel).
 
![ava_package_fehler500](https://user-images.githubusercontent.com/45172978/91311643-9ac53880-e7b3-11ea-90a2-f6716139e4fa.jpg)

KBART: 
[hbz.ava.watch_27 July 2020_kbart.txt](https://github.com/hbz/laser-ygor/files/5130251/hbz.ava.watch_27.July.2020_kbart.txt)

**Comment by philboeselager** [comment]
@MiriKon Hattest Du die gleiche CuratoryGroup angegeben? Die abgebildete Fehlermeldung sagt, dass dort (nur) "hbz" zugelassen ist. Ansonsten kann ich dazu wenig sagen, da ich auch nicht auf die Server-Logs drauf komme. Ich kann die Frage an nur an hornmo weiterleiten.

**Comment by MiriKon** [comment]
Genau, ich bin immer mit hbz als curatory group drin - sollte dann ja eigentlich kein Problem sein...

**Comment by philboeselager** [comment]
@hornmo Hier kann ich keinen spezifischen Fehler erkennen und auch nicht analysieren, weil ich keinen Einblick in die Logs habe. Kannst Du hierzu mehr sagen?

**Comment by hornmo** [comment]
Ein grundlegendes Problem was ich hier sehe ist der fehlerhafte Wert für `publication_type` in der Datei. Hier sollte insbesondere wenn es sicher keine Werte für `online_identifier` bzw. `print_identifier` gibt immer `other` stehen. `Monograph` wird immer als BookInstance angelegt und dementsprechend auch gegen alle eBooks gematcht, was zu fehlerhaften Merges führt.

Was den generischen Fehler bei der Paketeinspielung betrift, bin ich noch am nachforschen.

**Comment by philboeselager** [comment]
@hornmo Ich vermute nach wie vor ein grundlegendes Problem beim Update von Paketen. Denn: wenn ich die Daten aus [Herdt](https://herdt-campus.com/kbart/de) in ein neues Paket hochlade (ohne Anreicherung), erhalte ich folgendes GOKb-Feedback:

- Status:	OK
- Nachricht:	Created/Updated package 273 HERDT 52 with 906 TIPPs. (Previously: 0, Newly Retired/Deleted: 0)
- Intakt:	906
- Fehlerhaft:	null

Lade ich die selben Daten aus der selben Verarbeitung mit den selben Settings (selber Paketname) noch einmal hoch, erhalte ich:

- Status:	ERROR
- Nachricht:	Package referencing failed with exception!
- Intakt:	896
- Fehlerhaft:	2
  1	global=[{code=500, message=There was an exception while trying to referencing the Package, data={nominalProvider=HERDT-Verlag für Bildungsmedien GmbH, generateToken=true, identifiers=[], name=273 HERDT 52, nominalPlatform={name=HERDTCampus, primaryUrl=http://herdt-campus.de/}, curatoryGroups=[LAS:eR]}}]
  2	tipps=[]

Das macht so nicht so richtig Sinn, oder?

**Comment by MiriKon** [comment]
Ende der letzten Woche hatten wir die AVA KBART versucht auf einzuspielen - dieses Mal mit "other" als publication_type. Beim Senden des Packages an die GOKb blieb die Fortschrittleiste allerdings bei 0% hängen, so dass das Paket auf QA nicht eingespielt werden konnte.

**Comment by MiriKon** [comment]
[hbz.ava.watch_27 July 2020_kbart_other.txt](https://github.com/hbz/laser-ygor/files/5182128/hbz.ava.watch_27.July.2020_kbart_other.txt)
[hbz.ava.watch_27 July 2020_kbart_other.xlsx](https://github.com/hbz/laser-ygor/files/5182129/hbz.ava.watch_27.July.2020_kbart_other.xlsx)

**Comment by darupp** [comment]
phaeton-qa, 8.9.0: Upload der AVA-Title wirft Fehler
## Title-Upload
### Request-Body
```
[{
  "dateFirstOnline" : "2017-01-01",
  "identifiers" : [ {
    "value" : "ava-2019-00124",
    "type" : "ava"
  } ],
  "firstAuthor" : "Widad Shafakoj",
  "name" : "17",
  "type" : "other",
  "subject_reference" : "Lifestyle"
}]
```
### Response
```
{
    "results": [
        {
            "result": "ERROR",
            "message": "There was an error trying to reference title 17!",
            "baddata": {
                "identifiers": [
                    {
                        "type": "ava",
                        "value": "ava-2019-00124"
                    }
                ],
                "subject_reference": "Lifestyle",
                "name": "17",
                "dateFirstOnline": "2017-01-01",
                "type": "other",
                "firstAuthor": "Widad Shafakoj"
            }
        }
    ]
}
```

## Package-Upload
### Request-Body
```
{
  "packageHeader" : {
    "nominalProvider" : "AVA Library",
    "name" : "AVA Watch",
    "nominalPlatform" : {
      "name" : "AVA Library hbz Platform",
      "primaryUrl" : "https://hbz.ava.watch"
    },
    "curatoryGroups" : [ "hbz" ],
    "identifiers" : [ ]
  },
  "tipps" : [ {
    "coverage" : [ {
      "coverageDepth" : "Fulltext",
      "coverageNote" : "01: 14: 00"
    } ],
    "title" : {
      "identifiers" : [ {
        "value" : "ava-2019-00124",
        "type" : "ava"
      } ],
      "name" : "17",
      "type" : "other"
    },
    "platform" : {
      "name" : "AVA Library hbz Platform",
      "primaryUrl" : "https://hbz.ava.watch"
    },
    "url" : "https://hbz.ava.watch/film/17/",
    "subject_reference" : "Lifestyle"
  }
  ]}
```
### Response
```
{
    "result": "ERROR",
    "message": "Package referencing failed with exception!",
    "code": 500,
    "errors": {
        "global": [
            {
                "code": 500,
                "message": "There was an exception while trying to referencing the Package",
                "data": {
                    "nominalProvider": "AVA Library",
                    "identifiers": [],
                    "name": "AVA Watch",
                    "nominalPlatform": {
                        "name": "AVA Library hbz Platform",
                        "primaryUrl": "https://hbz.ava.watch"
                    },
                    "curatoryGroups": [
                        "hbz"
                    ]
                }
            }
        ],
        "tipps": []
    }
}
```

**Comment by MiriKon** [comment]
Das Senden des Pakets an die GOKb QA hat nun heute geklappt, wobei die Angaben und die Datei exakt dieselben waren wir letzte Woche

**Comment by darupp** [comment]
Mein Test klappte nicht, weil zwei Namensräume AVA existierten.

**Comment by philboeselager** [comment]
@darupp : Die beschriebenen Fehler sind anscheinend keine Fehlverhalten in Ygor, sondern Matching-Probleme in der GOKb. Zu `There was an exception while trying to referencing the Package` hatte ich oben auch bereits kommentiert. hornmo ist in der Untersuchung.

**Comment by darupp** [comment]
@hornmo Kannst Du hierzu schon was sagen? Auf QA ist der Fehler heute wieder geschehen.

**Comment by philboeselager** [comment]
In der Zwischenzeit erledigt.
