### ISSUE TITLE
Filmfriend KBART-Einspielung

### ISSUE THREAD

**Issue by MiriKon** [hbz/laser-ygor#280]
In Ygor (https://gokb.org/ygor) habe ich die KBART-Datei für das neue Filmfriend Konsortium hochgeladen (als publication_type mit "other"). 
[filmfriend_august_other_category.txt](https://github.com/hbz/laser-ygor/files/5130226/filmfriend_august_other_category.txt)

Beim Prozessieren wurden 2 Titel als zu überprüfen (orange) angezeigt (Meldung: Identifikatoren-Dubletten : ZdbIdentifier : filmwerte GmbH). Ich habe die Titel hochgespielt, dabei wurden dann aber die 2 Titel als fehlerhaft gemeldet und konnten nicht eingespielt werden (s. Screenshot)
![filmfriend_ygor_titel_senden](https://user-images.githubusercontent.com/45172978/91312179-3d7db700-e7b4-11ea-898c-e05a415c4d69.jpg)

Ich habe dann mal getestet das Paket an die GOKb ohne die beiden Titel zu senden, es konnte aber nicht gesendet werden (s. Screenshot 2)
![filmfriend_ygor_paket_senden](https://user-images.githubusercontent.com/45172978/91312321-669e4780-e7b4-11ea-9dbe-51b5c70d92d4.jpg)

Fazit: kein Titel wurde eingespielt für das Paket.

**Comment by philboeselager** [comment]
Der Fehler, der hier erkennbar ist, ist: beide "gelben" Titel haben als Eintrag im Feld `zdb_id` : "filmwerte Gmb-H". Deshalb werden sie in Ygor gelb markiert, was plausibel ist, da es sich um Einträge mit `publication_type` "other" handelt.

Meine Vermutung ist, dass diese Unterscheidung GOKb-seitig nicht gemacht wird, sondern dass dort festgestellt wird, dass es sich um einen "ernsten" Fehler handelt, und dass deswegen das ganze Paket abgelehnt wird.

Kannst Du das bestätigen, @hornmo ?

**Comment by hornmo** [comment]
Das ist korrekt. Die Werte für den Namensraum `zdb` werden in der GOKb auf ihre Form validiert, und fehlerhafte Werte führen zur Ablehnung des gesamten Titels, des TIPPs und somit auch des Pakets. Dem zweiten Screenshot nach sieht es so aus, als ob das Entfernen der Titel nicht registriert wurde, da die Fehler wieder die beiden Titel betreffen.

**Comment by philboeselager** [comment]
@hornmo Welche Felder sind noch derart kritisch, dass sie zur Ablehnung des ganzen Paket's führen?

@MiriKon Es gibt theoretisch 2 Strategien, damit umzugehen.

a) Die "kritischen" Felder werden auch für `publication_type` "other" rot markiert. Dann werden die zugehörigen Zeilen / Einträge nicht mit an die GOKb gesendet. Vermeidet Paket-Ablehnung, wirft aber auf Nutzerseite die Frage auf, warum Daten fehlen.

b) die GOKb akzeptiert fehlerhafte ZDB-IDs für `publication_type` "other". Das wäre aber mit hornmo abzustimmen und ist kein Ygor-Issue.

**Comment by MiriKon** [comment]
Hat jetzt geklappt - das Problem waren die verschobenen Spalten bei 2 Titeln (Spalte 1750 und 1871) für title_id und publisher_name . Die Rückmeldung von Ygor sollten wir aber nochmal im Hinterkopf behalten, weil diese Error Meldung nicht so hilfreich ist. 

Eine Sache ist mir Ygorseitig noch aufgefallen: wenn ich die KBART-Datei prozessiert habe, sehe ich nicht direkt aufgeführt welche Titel korrekt/fehlerhaft ggf. waren, sondern diese Sicht: 

![filmfriend_ygor_rückmeldung_sept](https://user-images.githubusercontent.com/45172978/91991931-d459ee80-ed33-11ea-9431-88c9bd29f30e.jpg)

Ich muss dann aktualisieren und dann kommt die richtige Rückmeldung welche Titel grün/orange/rot waren.

**Comment by philboeselager** [comment]
> Ich muss dann aktualisieren und dann kommt die richtige Rückmeldung welche Titel grün/orange/rot waren.

Ja, das ist bislang leider so. Vermutlich tritt es bei größeren Datenmengen auf. Das könnte auf ein Timeout in einer UI-Abfrage hindeuten. Das muss behoben werden.

**Comment by philboeselager** [comment]
> Die Rückmeldung von Ygor sollten wir aber nochmal im Hinterkopf behalten, weil diese Error Meldung nicht so hilfreich ist.

Das Problem ist, dass die Fehlermeldung erst an einem viel späteren Zeitpunkt (aus einem ganz "anderen" Anlass heraus) erzeugt wird. Deshalb hat sie auch nichts mit dem eigentlichen Problem zu tun.

Was hier also eigentlich hilfreich wäre, ist eine semantische Überprüfung der Tabelle, um zu checken, ob in einzelnen Zeilen Inhalte durcheinander gepurzelt sind. Nur wird Ygor dabei vermutlich sehr schnell an Grenzen stoßen, da das eigentlich eine human-intellektuelle Aufgabe ist. Wir könnten aber ein paar generische Kriterien sammeln, auf welche zu überprüfen wäre.

**Comment by philboeselager** [comment]
Habe die offenen Punkte in entsprechende Issues überführt:

- https://github.com/hbz/laser-ygor/issues/281
- https://github.com/hbz/laser-ygor/issues/282

Damit ist dieses Ticket erledigt.

**Comment by darupp** [comment]
Ich mache das Ticket wieder auf, weil ich speziell für den hier genannten Fehler folgende Lösung vorschlage:

ZDB-IDs schon YGOR-seitig validieren, möglichst identisch mit der GOKb-Validierung, und die Records von nicht validierten ZDB-IDs in den roten Bereich zu schieben. Davon unbenommen sollen Journals mit fehlenden ZDB-IDs weiterhin in der gelben Sektion verbleiben.

**Comment by philboeselager** [comment]
> ZDB-IDs schon YGOR-seitig validieren, möglichst identisch mit der GOKb-Validierung, und die Records von nicht validierten ZDB-IDs in den roten Bereich zu schieben. Davon unbenommen sollen Journals mit fehlenden ZDB-IDs weiterhin in der gelben Sektion verbleiben.

Das hatten @MiriKon und ich diskutiert. Es gibt zwei Bedenken.

1. ZDB-IDs sind für den `publication_type` "other" nicht kritisch. Im Grunde kommen sie gar nicht vor. Praktisch sollten sie also auch nicht als kritisch behandelt werden. Wenn man in der Ygor-Konfiguration eine fehlerhafte ZDB-ID als kritisch definiert, was ohne Weiteres möglich ist, bedient man die Constraints der GOKb, aber nicht die inhaltliche Realität. Anders ausgedrückt: man programmiert technisch orientiert, nicht fachlich. (Wenn wir das System fachlich / inhaltlich verbessern möchten, dürfen wir die optimierbaren Punkte nicht zementieren.)
2. Im Fall automatischer Updates werden "other"-Einträge mit fehlerhafter ZDB-ID einfach herausgefiltert, ohne dass ein Grund erkennbar ist. Das erzeugt Intransparenz.

Dieser Argumentation folgend wäre es also vermutlich richtig, in der GOKb die Behandlung von Identifieren in Abhängigkeit vom `publication_type` zu implementieren. Dafür müssten wir noch ein Ticket anlegen, glaube ich. Vermutlich würde das aber einen großen Aufwand mit sich bringen.

**Comment by philboeselager** [comment]
Um die Intransparenz im Falle eines automatischen Updates zu reduzieren, und um einfacher nachvollziehbar zu machen, welche Daten in einem Paket nicht enthalten sind, könnte Ygor beim Paket-Upload eine Information über nicht enthaltene Daten (z. B. Titelnamen) in einem gesammalten "Sonstiges"-Feld an den Paket-Header anfügen.

@hornmo Gäbe es dafür auf GOKb-Seite ein geeignetes Feld?

**Comment by philboeselager** [comment]
Überführt zu GOKb.
