### ISSUE TITLE
Delimiter-Auswahl entfernen

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#284]
Niedrige Prio!

Da der KBART-Standard Tab-getrennte Dateien vorschreibt, kann die Delimiter-Auswahl im Zug der GUI-Vereinfachung entfernt werden bzw. bei Einbettung in die neue GUI ignoriert werden.

**Comment by philboeselager** [comment]
Da der Aufwand sehr gering ist und die Eingabe-Möglichkeit seit längerem eine "Täuschung" der Nutzenden darstellt, weil die tatsächliche Auswahl des angewendeten Delimiter's bereits automatisch anhand der in der Datei enthaltenen Delimiter erfolgt (bislang fehlerlos), sollte dieses Ticket doch schnell bearbeitet werden.

**Comment by darupp** [comment]
Okay, gerne!
