### ISSUE TITLE
Automatisches Update : prüfe Zeile

### ISSUE THREAD

**Issue by philboeselager** [hbz/laser-ygor#286]
Im Falle eines Updates wird anhand der neu hinzuzufügenden Spalte `last_changed` geprüft, ob der dort enthaltene Zeitstempel 
aktueller ist, als das Datum, an dem das Paket zuletzt eingespielt bzw. aktualisiert wurde. Ist dies der Fall, wird die entsprechende Zeile geupdatet - jedoch nicht (zwangsläufig) die gesamte Datei.

Dabei ist zu definieren, in welchen Format der Zeitstempel vorliegen muss.

**Comment by philboeselager** [comment]
@darupp Die KBart-Spezifikation liefert die folgenden Formate für Zeitangaben:

- YYYY
- YYYY-MM
- YYYY-MM-DD

Eine Angabe mit geringerer Granularität als `YYYY-MM-DD` scheint aber hier nicht sinnvoll und könnte daher ausgeschlossen werden!?

**Comment by darupp** [comment]
Genau, eine geringere Granularität brauchen wir nicht.

**Comment by philboeselager** [comment]
Implementiert.
