### ISSUE TITLE
Automatisierung: Übernahme der notwendigen Daten aus der GOKb

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#294]
Korrespondierendes GOKb-Ticket: https://github.com/openlibraryenvironment/gokb/issues/327

Für die Automatisierung sollen (zusätzlich zu den bisherigen dort hinterlegten Daten wie Paketreferenz und Token ) grundlegend notwendige Daten aus der GOKb genommen werden, wenn von dort aus die Anreicherung gestartet wird: 

  * URL zum automatischen Einspielen
  * Update-Intervall
  * Grundeinstellungen YGOR
    * Namensraum für _title_id_ (Auswahl: Eigener, DOI,...)
    * (Anreicherungsschnittstellen)

**Comment by philboeselager** [comment]
Implementiert.
