### ISSUE TITLE
Fehlende Plattform bei manchen TIPPS

### ISSUE THREAD

**Issue by HebisJC** [hbz/laser-ygor#3]
Beim Export von in YGOR generierten Package-JSONs fehlen bei manchen TIPPS Informationen zur Plattform (platform->name und platform->primaryURL).

Leider werden die Titel solcher Packages nicht an das Paket gehängt, wenn auch nur einer der TIPPS beim Import des Package-JSON ohne Plattform daherkommt. Vereinzelte Tests haben ergeben, dass hierbei im Konkreten platform->name obligatorisch zu sein scheint.

**Comment by klodav** [comment]
Der aktuelle Workflow sieht so aus:

_1._ packageHeader.nominalProvider wird über die Eingabemaske in Schritt 2 (Auswahl Plattform) gesetzt.

_2._ tipp.url wird aus den API-Calls (PICA-Felder 009Pa) übernommen, falls die URL-Authority gegen _1._ matcht

_3._ tipp.plattform.primaryUrl und tipp.plattform.name werden von _2._ übernommen, falls _2._ gültig interpretiert wurde

Wir diskutieren noch, ob es Gründe gegen eine direkte Übernahme von _1._ nach _3._ gibt.

**Comment by klodav** [comment]
Version 0.20

Im Schritt **Paketdaten festlegen** wird eine Liste mit Plattformen zur Auswahl angeboten.
Diese Liste wird direkt aus der GOKb-Datenbank gelesen. 

Falls bei einer Plattform jedoch kein URL hinterlegt ist, kann der oben beschriebene Workflow nicht positiv durchlaufen werden. Es werden also weder TIPP->url noch TIPP->platform->name und/oder TIPP->platform->primaryURL erzeugt.

Daher werden Plattformen ohne hinterlegten URL neuerdings optisch hervorgehoben.

**Comment by klodav** [comment]
Version 0.21

Der Workflow wurde angepasst:

TIPP->platform->name und TIPP->platform->primaryURL werden **immer** aus dem PackageHeader übernommen.

Bei der Prüfung des TIPP->url werden nun Subdomains berücksichtigt (bsp. matcht http://blau.springhaus.de/journal/123 erfolgreich gegen http://springhaus.de)
