### ISSUE TITLE
Reihe, Fachbereich, Listenpreis auf TIPP statt Titel beziehen

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#306]
Siehe https://github.com/openlibraryenvironment/gokb/issues/270

**Comment by philboeselager** [comment]
Erledigt mit 6e0c7af0f9925e0b87ee2fe2ccec6751d525a9bf.
Mangels Daten ist das noch nicht getestet.

**Comment by philboeselager** [comment]
@darupp Bitte schließen, wenn Ergebnis wie gewünscht.

**Comment by darupp** [comment]
Die neuen Felder sollen ins `tipp`-Objekt des `Package`-JSON integriert werden, siehe https://github.com/openlibraryenvironment/gokb/issues/270#issuecomment-697293490.

Die Verarbeitung sieht indes gut aus, wie das `Title`-JSON zeigt.

Testdatei anhängend: 
[Springer_Global_Springer_Behavioral_Science_and_Psychology_test_reihe_fachbereich_preise.txt](https://github.com/hbz/laser-ygor/files/5420927/Springer_Global_Springer_Behavioral_Science_and_Psychology_test_reihe_fachbereich_preise.txt)

**Comment by philboeselager** [comment]
@darupp Deployed auf DEV und QA (https://github.com/hbz/laser-ygor/commit/7b20f19339f89e0ba4b19abee1e2a4bbb7cd03f1). Bitte schließen, wenn Ergebnis wie gewünscht.

**Comment by darupp** [comment]
Getestet und funktioniert.

Testdatei und Ergebnis angehängt.

[Test_Reihe_Fachbereich_Listenpreis.zip](https://github.com/hbz/laser-ygor/files/5421512/Test_Reihe_Fachbereich_Listenpreis.zip)
