### ISSUE TITLE
Skript (oder manuelle Übertragung) für die einmalige Übertragung von Daten zum Automatischen Paketimport in die GOKb

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#314]
Zurzeit werden Daten für den Paketimport in YGOR selbst gespeichert. Perspektivisch sollen sie in der GOKb (In Source) gespeichert werden. Zu einem Tag X müssen die existierenden Daten entsprechend übertragen werden.

**Comment by philboeselager** [comment]
Ist implementiert.
