### ISSUE TITLE
Verhindere zu viele parallele Sessions beim regelmäßigen Aufruf von Root

### ISSUE THREAD

**Issue by philboeselager** [hbz/laser-ygor#326]
Offensichtlich führt der Aufruf von Ygor zu neuen GOKb-Sessions. Da das interne Monit-Tool die Verfügbarkeit von Ygor auf diese Weise permanent checkt, entstehen auf diese Weise bis zu 180 parallele, offene GOKb-Sessions.

Ziel ist es daher, zu unterdrücken, dass der Aufruf von Ygor automatisch zu einer neuen GOKb-Session führt.

**Comment by philboeselager** [comment]
Durch Code-Analyse konnte ich keinen Zusammenhang herstellen. Der Aufruf von `/` bringt keinen Code zur Ausführung, in dem ein GOKb-Request hergestellt wird oder ein sonstiger Zusammenhang zu einer GOKb-Session erkennbar ist. Auch das Befragen von gängigen Suchmaschinen brachte keinen näheren Aufschluss.

@croqueGrec09 @hornmo Ist es möglich, dass hier ein Missverständnis vorliegt, und die Sessions eigentlich durch den direkten Check von Monit auf `/` der GOKb geöffnet werden?

**Comment by croqueGrec09** [comment]
Monit prüft die Erreichbarkeit der GOKb ebenso, wie die von Ygor.

**Comment by philboeselager** [comment]
Das Issue wurde nach Präzisierung des Problems umbenannt.
