### ISSUE TITLE
Fehlermeldung beim Einlesen einer KBART-Datei

### ISSUE THREAD

**Issue by peterboehm** [hbz/laser-ygor#34]
Beim Einlesen in Ygor (v. 0.29; 0.30) auf Phaeton einer aus dem Statistikserver exportierten KBART-Datei (TSV oder CSV mit Semikola) erscheint nach dem letzten Formularschritt die Fehlermeldung:

`java.lang.IllegalArgumentException: Mapping for publication_title not found, expected one of [access_type, coverage_depth, Crossaccess, date_first_issue_online, date_last_issue_online, date_monograph_published_online, date_monograph_published_print, embargo_info, Fachgebiet (DDC), first_author, first_editor, ID, monograph_edition, monograph_volume, notes, num_first_issue_online, num_first_vol_online, num_last_issue_online, num_last_vol_online, Online ISSN, online_identifier, parent_publication_title_id, preceding_publication_title_id, Print ISSN, print_identifier, proprietaere ID, publication_type, publisher_name, Sachgruppe (DDC), title_id, title_url, ZDB-ID, "publication_title"] at org.apache.commons.csv.CSVRecord.get(CSVRecord.java:104) at org.apache.commons.csv.CSVRecord$get$0.call( .. `

Die Header-Zeile der importierten Dateien lautet

`"publication_title";"print_identifier";"online_identifier";"date_first_issue_online";"num_first_vol_online";"num_first_issue_online";"date_last_issue_online";"num_last_vol_online";"num_last_issue_online";"title_url";"first_author";"title_id";"embargo_info";"coverage_depth";"notes";"publisher_name";"publication_type";"date_monograph_published_print";"date_monograph_published_online";"monograph_volume";"monograph_edition";"first_editor";"parent_publication_title_id";"preceding_publication_title_id";"access_type";"ID";"Sachgruppe (DDC)";"Fachgebiet (DDC)";"Print ISSN";"Online ISSN";"ZDB-ID";"proprietaere ID";"Crossaccess"`

**Comment by philboeselager** [comment]
Das Problem ist an dieser Stelle das (unsichtbare) [BOM](https://de.wikipedia.org/wiki/Byte_Order_Mark). Behoben in https://github.com/hbz/laser-ygor/commit/aefe78190c3dcb175ae5eeb491c957fe33f6b0a4 .

**Comment by philboeselager** [comment]
Done in aefe78190c3dcb175ae5eeb491c957fe33f6b0a4.
