### ISSUE TITLE
Übernahme von Daten aus access_start_date und access_start_date

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#38]
Es sollen weitere Felder aus den KBART-Dateien verarbeitet werden: access_start_date und access_end_date

Die Validierung erfolgt entsprechend der anderen Datumsfelder, zum Beispiel date_first_issue_online. 

Die Feldihalte sollen im JSON für die package-API der GOKb entsprechend ausgewiesen werden, als accessEnd und accessStart im Tipp (zur Zeit werden die Felder freigelassen):

```
"tipps" : [
    {
        "accessEnd" : "",
        "accessStart" : "",
        ...
```
Die korrekte Verarbeitung dieser Felder erfolgt über die API der GOKb, müsste aber im Einzelfall getestet werden.

**Comment by philboeselager** [comment]
Deployed mit https://github.com/hbz/laser-ygor/commit/f48c829bf2a2fe14b1d487f5aab2f9cd804a0c11 .

**Comment by darupp** [comment]
Ist es möglich, diese Felder mit vertretbarem Aufwand nicht obligatorisch zu machen? Im Augenblick scheitert das Verarbeiten der Datei, wenn die Header nicht existieren.

**Comment by philboeselager** [comment]
Erledigt in https://github.com/hbz/laser-ygor/commit/41a32e64074f69944be8fddf6a34582899fde2de .

**Comment by darupp** [comment]
Der Fehler tritt auf ygor-dev immer noch auf: http://phaeton.hbz-nrw.de:9000/ygor

**Comment by darupp** [comment]
Zusätzlich muss darauf geachtet werden, dass im TSV keine Fehlermeldung auftritt, wenn zwar die Header access_start_date und access_end_date fehlen, aber es im Body der Tabelle noch entsprechende Tabs gibt.

**Comment by darupp** [comment]
Es kann sein - als reine Theorie - dass YGOR zwar den Spaltenheader mittlerweile ignoriert, aber weiterhin die Spalten selbst nach diesen Feldern durchforstet.

Fehlermeldung hier explizit:


java.lang.IllegalArgumentException: Mapping for access_start_date not found, expected one of [coverage_depth, date_first_issue_online, date_last_issue_online, embargo_info, notes, num_first_issue_online, num_first_vol_online, num_last_issue_online, num_last_vol_online, online_identifier, print_identifier, publication_title, title_url] at org.apache.commons.csv.CSVRecord.get(CSVRecord.java:104) at org.apache.commons.csv.CSVRecord$get$0.call(Unknown Source) at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) at de.hbznrw.ygor.processing.KbartProcessor$_initData_closure1$_clo ..

**Comment by philboeselager** [comment]
> Zusätzlich muss darauf geachtet werden, dass im TSV keine Fehlermeldung auftritt, wenn zwar die Header access_start_date und access_end_date fehlen, aber es im Body der Tabelle noch entsprechende Tabs gibt.

@darupp : dann liegt ein defektes Dateiformat als Input vor, bei dem aufgrund der einfachen Formatierung von .csv bzw. .tsv nicht mehr zuordbar ist, welcher Wert zur welchem Header-Eintrag ("Spalte") gehört, richtig? Solche Dateien sollten nicht prozessiert werden. Ein Abbruch mit Fehlermeldung ist hier das bessere Verhalten.

**Comment by darupp** [comment]
Nein, ich meine andersrum: Ich befürchte, dass YGOR noch die Tabs sucht, obwohl sie in korrekten Dateien nie existiert haben, weil access_start_date und access_end_date keine offiziellen KBART-Felder sind. Oben genannte Fehlermeldung tritt auf, wenn ich normale KBART-Dateien einspiele. Sobald ich access_start_date und access_end_date als Spaltenheader setze, funktioniert es.

**Comment by darupp** [comment]
Problem tritt weiterhin auf

**Comment by philboeselager** [comment]
Solved.
