### ISSUE TITLE
tipps > platform > name: blanc in URL

### ISSUE THREAD

**Issue by lemfra** [hbz/laser-ygor#4]
Beim Package-Import über crossReferencePackage-API wird folgende Fehlermeldung geworfen nachdem das Paket ohne TIPPs angelegt wurde:

"WARN  gokb.IntegrationController  - Not valid after platform validation [name:http: //link.springer.com, primaryUrl:http://link.springer.com]"

H I N W E I S:
Die URL in [name: enthält ein Blanc

U R S A C H E:
Im Package-JSON generiert Ygor in "tipps > platform > name" ein Blanc in der URL

T E S T:
Habe das entsprechende JSON-File auf zwölf Einträge gekürzt und dort in den URLs die Blanc entfernt.

E R G E B N I S:
Beim Upload auf phaeton wird das Paket korrekt angelegt und mit den TIPPs versehen.

**Comment by klodav** [comment]
Das Leerzeichen wurde durch den String-Normalisierer eingefügt, da dieser üblicherweise keine URL verarbeitet.

Ist in Version 0.14 behoben.
