### ISSUE TITLE
Paketupload funktioniert nicht

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#41]
Der upload des anhängenden Paketes funkioniert auf der Testinstanz mit phaeton-dev nicht. Der Titelupload funktioniert, aber nicht der Paketupload
[EmeraldPublishing_Global_EmeraldMarketingeJournalCollection_2018-02-06.txt](https://github.com/hbz/laser-ygor/files/1731487/EmeraldPublishing_Global_EmeraldMarketingeJournalCollection_2018-02-06.txt)

**Comment by philboeselager** [comment]
Gefixt in https://github.com/hbz/laser-ygor/commit/9f30d0623b259779b50524a8d2fbaa3179786a27 .
