### ISSUE TITLE
Felder zu coverage falsch validiert

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#43]
Die Felder

    num_first_vol_online
    num_first_issue_online
    num_last_vol_online
    num_last_issue_online

werden im Augenblick auf Integer-Werte validiert. Das ist falsch. In der GOKb sind die Felder als varchar(255) definiert. Insofern müssten diese Felder auf String-Werte validiert werden und entspechend ins JSON geschrieben werden.

**Comment by philboeselager** [comment]
Merged in https://github.com/hbz/laser-ygor/commit/f92e0c9d33d9c356fffdc07d818a17f879a29a67 .
