### ISSUE TITLE
Einstiegspunkt für die Anreicherung

### ISSUE THREAD

**Issue by hornmo** [hbz/laser-ygor#45]
Aktuell ist die Auswahl eines Identifier-Typs für das Matching mit ZDB-Daten erforderlich. Problematisch ist, dass dies für die vollständige Abbildung der Titelliste voraussetzt, dass der jeweilige ID-Typ für jeden Titel vorhanden sein muss. Ist dies nicht der Fall, wird der Titel für die Paket-Generierung zur Zeit einfach weggelassen. Dies verursacht eine schwer nachzuvollziehende Abweichung des Paketzuschnitts in der GOKb von der ursprünglichen Titelliste. Um dies zu verhindern, sollte über folgende Änderungen nachgedacht werden:

* Automatisches Ausweichen auf andere IDs
* Verhinderung des Einspielvorgangs (oder zumindest deutliche Warnungen), falls ein oder mehrere TIPPs gar nicht erzeugt werden konnten
* Ausgabe von Konfliktinformationen mit Hinweis auf spezifische Zeilen in der KBART-Datei

**Comment by darupp** [comment]
Lösungsmöglichkeit: Anstatt den Identifier anzugeben, sollte eine Prioritätenreihenfolge der Identifikatoren festgelegt sein: ZDB-ID, eISSN, print-ISSN.

**Comment by philboeselager** [comment]
Umgesetzt in https://github.com/hbz/laser-ygor/commit/7ac0e6635bf0040db18e5ab5fca3692952dff67b. Review und Test ausstehend.
