### ISSUE TITLE
Titelinformationen aus Vorgänger-Nachfolger-Beziehungen sind unvollständig

### ISSUE THREAD

**Issue by hornmo** [hbz/laser-ygor#46]
Die aktuelle Methode zur Generierung von Titelhistorien beschränkt sich auf die Auswertung des jeweiligen Felds (039E) in dem ausgewählten Titel. Dies bewirkt, dass die erzeugten JSON-Objekte für den verknüpften Titel unvollständig sind:

* Eine eventuelle Titelkorrektur aus Feld 025@ wird nicht berücksichtigt
* ISSNs des verknüpften Titels werden nicht verwertet (nur die ZDB-ID wird gesetzt)
* Es findet keine Überprüfung statt, ob der verknüpfte Titel ebenfalls ein elektronisches Medium ist

Um diesen Problemen entgegenzuwirken, müsste für jedes History-Event eine separate Titelabfrage gestartet werden, und der entsprechende Titel nach dem gleichen Verfahren wie alle direkt verzeichneten Titel generiert werden.

Dies würde allerdings auch neue Konfliktfälle beim Einspielen in die GOKb erzeugen, falls es uneindeutige Kombinationen von ZDB-ID und (e)ISSNs in den entsprechenden Titeln gibt.

**Comment by philboeselager** [comment]
In der [ZDB-Konkordanz-Übersicht](https://www.zeitschriftendatenbank.de/fileadmin/user_upload/ZDB/pdf/services/Konkordanz_PICA-MARC21_Titel.pdf) steht zu `025@` : "Ansetzungssachtitel" bzw. "Title proper/short title". Wie ist der Zusammenhang zur Titel**korrektur** zu verstehen, @hornmo ?

**Comment by hornmo** [comment]
@philboeselager der Ansetzungssachtitel in `025@` kommt nur in nach einem älteren Regelwerk erschlossenen Titeln vor, und enthält z.B bei Unterreihen einer Zeitschrift einen spezifischeren Titel mit "Ordnungshilfen" (https://www.zeitschriftendatenbank.de/erschliessung/arbeitsunterlagen/zeta/3220/) als den Hauptsachtitel in `021A$a`. Dies ist zum Beispiel bei Titelsplits zur Unterscheidung des neuen Titels von dem vereinigten Vorgängertitel hilfreich: [The journal of physical chemistry](http://services.dnb.de/sru/zdb?version=1.1&operation=searchRetrieve&query=dnb.zdbid=2256522-X%20and%20dnb.frm=O&maximumRecords=2&recordSchema=PicaPlus-xml)

021A$a  => The @journal of physical chemistry <Washington, DC>
039E$Y  => The @journal of physical chemistry <Washington, DC>
025@$a => The @journal of physical chemistry <Washington, DC> / C

Für neuere Zeitschriften müsste man sich etwas anderes überlegen, etwa eine manuelle Verknüpfung von `021A$a` +  mit Infos aus Feldern in `021C` ([PICA 4005/021C: Titel von Unterreihen fortlaufender Ressourcen](https://www.zeitschriftendatenbank.de/fileadmin/user_upload/ZDB/pdf/zdbformat/4005.pdf)).

**Comment by philboeselager** [comment]
@hornmo Must an existent title variation (`025@$a`) of a **linked** title overwrite the **linking** history event title (`039E$Y`)?

If this is not the case, my suggestion would be:

- `025@$a` overwrites `021@$a` (?)
- `039E$Y` remains untouched

However, this can possibly lead to mismatches between the linking `039E$Y` and the linked `025@$a`. (...in case there are such mismatches in the SRU API.) I assume, such mismatches would not be a problem for the GOKb.

**Comment by hornmo** [comment]
@philboeselager Ideally all title occurences should be build in the same way (see #101), regardless if they are in a history event or not.

**Comment by philboeselager** [comment]
@hornmo Right - thanks for the link. As this is not the main issue of this ticket, I will come back it when working on #101 (overlapping tickets / issues). Keeping it with a simpler solution here, as we used this ticket for work on deriving historyEvents from the refactored Ygor.
