### ISSUE TITLE
Bestimmung der Platformliste aus der GoKB funktioniert nicht

### ISSUE THREAD

**Issue by cjaegle** [hbz/laser-ygor#47]
Ich kann jetzt nicht sagen, ob es an einer falschen Ygor/GoKB Kombination liegt, jedoch wirft Ygor bei uns beim Versuch die (noch nicht verwendete?) GOKB API abzufragen eine Exception und verwendet die nicht mehr passende Fallback Liste. Die Datenbankabfrage nach den Platformen müsste funktioniert haben.

**Comment by philboeselager** [comment]
Ja, ist obsolet.
