### ISSUE TITLE
nominalPlatform: Im JSON zum Paket wird nominalPlatform mit URL gefüllt

### ISSUE THREAD

**Issue by HebisJC** [hbz/laser-ygor#5]
In den von Ygor exportierten JSONs werden unter nominalPlatform die Plattform-URL und unter nominalProvider der Plattformname hinterlegt. Das führt dazu, dass später in der GoKB bei der Paketübersicht im Feld "Nominal Platform" die Plattform-Url erscheint. Das Gleiche gilt dann auch für die Paketdetails.

Es gilt abzuklären, ob dieses Verhalten erwünscht ist, oder ob man an der Stelle in der Oberfläche lieber den eigentlichen Plattformnamen haben möchte.

**Comment by darupp** [comment]
Hier sollte tatsächlich unter "nominalPlatform" auf Paketebene der Plattformname der GOKb stehen. Zu prüfen ist da aber auf GOKb-Seite, ob in der Import-Schnittstelle hier irgendein Matching stattfindet. Das Import-Format ist hier dokumentiert: [https://wiki1.hbz-nrw.de/pages/viewpage.action?pageId=182091855]

**Comment by philboeselager** [comment]
In auf der verlinkten Wiki-Seite genannten Beispiel steht:

    "nominalPlatform" : "http://pubs.acs.org/archives/"

Ein Matching wird dort nur für `packageHeader->name` erwähnt. Im GOKb-Code konnte ich ein Matching bislang nicht feststellen.

**Comment by hornmo** [comment]
Die Schnittstelle wurde mittlerweile insofern angepasst, dass auch auf Paketebene die Plattform wie bei den TIPPs angegeben werden _kann_, d.h.
`
"nominalPlatform" : {
     "name" : "ACS Publications",
     "primaryUrl" : "http://pubs.acs.org"
}
`
ist jetzt möglich, wobei nur "name" ein Pflichtfeld ist. Wird nach alter Methode ein einfacher String übergeben, wird dieser zunächst als "name" behandelt. Im Anschluss wird aber überprüft, ob hier eigentlich eine URL übergeben wurde. Es wird immer sowohl über den Namen (bevorzugt), als auch über die URL (Fallback) gematcht.

Im Feld "nominalProvider" sollten ausschließlich Orgs stehen, über Plattformen wird hier nicht gematcht.

Beim Package-Matching werden nominalPlatform und nominalProvider nicht berücksichtigt.
