### ISSUE TITLE
Rückkompatibilität mit KBART Phase I

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#50]
Notes/coverage_notes: Der Name des Feldes hat sich bei KBART II geaendert, es werden aber nicht beide Namen unterstuetzt, sondern nur noch der neue notes, so dass man z.B. die Dateien aus der EZB
nachbearbeiten müssen. Es sollten beide Feldbezeichner möglich sein.

**Comment by philboeselager** [comment]
Done in 70be502d2ac4612185194a90197496a3c7d5c7a1 .

**Comment by darupp** [comment]
Bei unserer Testdatei zu ACS funktioniert es nicht, wenn man "notes" in "coverage_notes" umbenennt: 

groovy.lang.MissingPropertyException: No such property: kbartKeys for class: de.hbznrw.ygor.connectors.DnbSruPicaConnector at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53) at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:52) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:296) at de.hbznrw.ygor.processing.KbartProcessor$_initData_closure1.doCall(KbartProcessor.groovy:115) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java: ..
