### ISSUE TITLE
Feld "ZDB-ID" korrekt matchen

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#51]
Spalte ZDB-ID: Die Spalte muesste eigentlich zdb_id und nicht ZDB-ID heissen, da die Spaltennamen bei KBART ueblicherweise klein geschrieben und durch Unterstriche getrennt sind. Die EZB verwendet zdb_id. Daher sollte sowohl "ZDB-ID" wie "zdb_id" akzeptiert werden.

**Comment by philboeselager** [comment]
Rückfrage grundsätzlicher Natur: soll Großschreibung bei alten Spaltennamen automatisch korrigiert (lower-cased) werden?

**Comment by darupp** [comment]
Ja, kann gemacht werden. Bei der zdb_id im speziellen bitte auch auf Bindestrich/Unterstrich achten.

**Comment by darupp** [comment]
Außerdem wird immer noch auf den Spaltennamen geprüft, ob er vorhanden ist. ZDB-ID ist aber kein Pflichtfeld, es darf daher keinen Abbruch geben.

**Comment by philboeselager** [comment]
Done in f3dc49565e89502d03b632375f2cda1461143b47 and b45bb6f734d211d4f9c64f4b7c0ad1de97a68216 .
