### ISSUE TITLE
Fehlermeldung bei fehlerhafter Übernahme von Plattform und Anbieter

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#52]
Es fehlt eine Fehlermeldung, wenn Plattform- und Anbieterliste nicht aus der GOKb geholt werden können.

**Comment by VolkerHBZ** [comment]
Was sollte denn in der Fehlermeldung drinstehen? "Es besteht gerade keine Verbindung zum Index, oder der Index ist leer oder er enthält keine Daten, die mit der Eingabe übereinstimmen. Bitte versuchen sie eine andere Eingabe oder versuchen sie es erneut, sobald die Verbindung wieder hergestellt werden konnte. Alternativ können sie auch eine Nachricht an gokb@hbz-nrw.de senden und ihr Problem schildern."

Was ich sagen will ist, daß ein offensichtlich leeres Suchfeld zwar meistens ein Fehler ist, aber keine endeutige Ursache hat und auch durchaus ein normales Verhalten sein kann. Eine Fehlermeldung an den User erreicht nicht die Person, die den Fehler auch beheben könnte. Sinnvoller wäre eine Meldung an den Admin des Servers, sobald der ES-Index nicht erreichbar ist.

**Comment by philboeselager** [comment]
Unklare Anforderung (siehe Kommentar) und veraltet. Bei bestehendem Interesse bitte wieder öffnen.
