### ISSUE TITLE
Fehler bei Volume und Issue-Angaben

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#58]
In der von Ygor generierten Package-Datei fehlen alle startVolume
(num_first_vol_online), endVolume (num_last_vol_online) und startIssue
(num_first_issue_online) Angaben aus der KBART-Datei. Die endIssue
(num_last_issue_online) sind teilweise vorhanden, offenbar aber nur die
Werte ab 10 aufwaerts (mit mindestens zwei Stellen?).

**Comment by philboeselager** [comment]
Deployed auf dev, qa und prod.
