### ISSUE TITLE
ZDB-SRU nicht mehr erreichbar

### ISSUE THREAD

**Issue by hornmo** [hbz/laser-ygor#59]
Aufgrund einer Änderung bei der DNB ist die bisherige Zugriffsmethode auf die ZDB-Daten über das GBV-SRU nicht mehr möglich. Als Lösung sollte zunächst wieder direkt auf das ZDB-SRU zugegriffen werden, auch wenn dort die Performance nicht besonders gut ist.

**Comment by berndoberknapp** [comment]
Es wäre denke ich sinnvoll, die Antworten zumindest kurzzeitig,z.B. für 24 Stunden, zu cachen. Das sollte eigentlich nicht besonders aufwendig sein?

**Comment by philboeselager** [comment]
Bis auf Weiteres umgesetzt in https://github.com/hbz/laser-ygor/commit/f07f29db02f89d0b5067b619be74946d38e2566d, ohne Caching. Wenn die Performance nicht hinreichend ist, bitte das Ticket mit entsprechendem Vermerk wieder öffnen.
