### ISSUE TITLE
nominalPlatform: Nach Anlegen eines GoKB-Pakets per JSON-Import ist Feld im Interface leer

### ISSUE THREAD

**Issue by HebisJC** [hbz/laser-ygor#6]
Beim Anlegen eines neuen Pakets über die JSON-Schnittstelle ist die "Nominal Platform" hinterher "empty", obwohl eindeutig im JSON sowohl "nominalPlatform", als auch "nominalProvider" angegeben waren. 

So geschehen bei den "ACS Journals" und bei "ACM Digital Library", wobei die Plattform bei Letzterem im späteren Verlauf doch noch vergeben wurde. Vermutung hier: das Paket wurde mehrmals über JSON importiert, möglicherweise hat ein weiterer Import das Anlegen der Plattform impliziert. Die Metadaten zur Plattform waren bei jedem Import identisch.

**Comment by HebisJC** [comment]
Das scheint immer nur dann zu passieren, wenn die Plattform das erste Mal verwendet wird beim Anlegen eines Pakets über den JSON-Import. Wenn die Plattform bereits bei einem früheren Paket verwendet wurde (auch wenn sie in dem Paket nicht korrekt auf der Oberfläche angezeigt wird), dann wird die Plattform beim nächsten Paket bzw. beim wiederholten Import desselben Pakets richtig dargestellt.

Ist mir inzwischen bei mehreren Paketen passiert. Ein gutes Beispiel zum Nachvollziehen ist SIAM.

Ist aber tatsächlich eigentlich kein Fehler bei Ygor, sondern eher bei der GoKB zu sehen.

**Comment by klodav** [comment]
Dann bitte bei Bedarf ein entsprechendes Ticket erstellen.
