### ISSUE TITLE
Probleme mit Platformmatching Ygor->GoKB

### ISSUE THREAD

**Issue by cjaegle** [hbz/laser-ygor#69]
Beim Hochladen eines Paketes über Ygor in die GoKB kann eine existierende Platform in der GoKB nicht verwendet werden. Es werden 2 neue Platformen angelegt und die Titel werden an die neuste Paltform angehängt.
Im folgenden Review Request Screenshot sieht man meinen Versuch initial ein Paket hochzuladen und im 2. Schritt ein Update des Paketes Hochzuladen. Es wurden jeweils 2 neue Platformen angelegt. Beim Update hingen die Tipps danach an der neusten erzeugten Platform. Bei den APS und ACS Platformen darunter muss wohl etwas ähnliches passiert sein.

![screenshot_20181001_112322](https://user-images.githubusercontent.com/2149533/46280928-82b7f080-c56d-11e8-913d-d480f9e55457.png)

Ygor 0.47
GoKB: 7.0.45 | v7_dev_integration | 155c933e4c62f0274bb5fc57f790a122dba59d7e

**Comment by philboeselager** [comment]
@cjaegle Nachdem das für mich zunächst wie ein Bug aussah, kann der Grund für das Verhalten nun auch darin liegen, dass

- es sich bei der Plattform um eine kuratierte Plattform handelt und
- der updatende User (hier anscheinend `admin`) nicht in der entsprechenden Kuratoren-Gruppe enthalten ist.

Testen lässt sich dies, indem dem User die Mitgliedschaft in den Kuratoren-Gruppen der betroffenen Plattformen hinzugefügt werden und ein neuer Update-Versuch vorgenommen wird.

**Comment by cjaegle** [comment]
Ich habe nun leider noch einige erfolglose Tests hinter mir. Bevor ich weiter auf meinen Testfall eingehe, wäre es vielleicht einfacher, wenn Ihr die von euch eingespielten Pakete untersucht, wo ja exakt dasselbe passiert sein müsste, also z.B: 
American Physical Society und
ACS Publications

Es sind hier auch einige unbenutzte Platformen erzeugt worden. Wenn man auf der Produktiv GoKB Instanz die Review Requests Rückwärts nach Timstamp sucht sind die gleich auf der ersten Seite zu finden

**Comment by cjaegle** [comment]
Ich habe mal in den GoKB Code geschaut. Es liegt wohl daran, dass das Platformmatching dort nicht zuschlägt. Dort wird anhand Namen und Url geprüft. 
Der Platformname wird nur berücksichtigt, wenn er mit http:// beginnt. Warum das Matching mit URL nicht funktioniert hat, weiß ich gerade nicht.
Jedenfalls funktioniert die Zuordnung, wenn ich den Platformnamen in der GoKB so abändere, dass er mit http:// beginnt. Das müssten wir dann denke ich in der GoKB ändern. (?)

**Comment by philboeselager** [comment]
@cjaegle Nach meinen Untersuchungen liegt das Neuanlegen der Plattform daran, dass bei der Datenanreicherung keine übereinstimmende Curatory Group ausgewählt wurde / angegeben werden konnte. Eine Übereinstimmung liegt vor, wenn:

- entweder mindestens eine Curatory Group exakt gleich eingegeben wurde (Groß-/ Kleinschreibung und Sonderzeichen sind relevant) und der User dieser Curatory Group zugeordnet ist,
- oder weder beim vorhandenen Paket noch beim Update desselben eine Curatory Group angegeben wurde.

Da dem bestehenden Paket [American Physical Society](https://phaeton.hbz-nrw.de/gokb/resource/show/org.gokb.cred.Package%3A396016) die Curatory Groups "hbz" und "LAS:eR" zugewiesen wurden (durch den User [`rupp`](https://phaeton.hbz-nrw.de/gokb/resource/show/org.gokb.cred.User%3A66874), der diesen CGs ebenfalls zugeordnet ist), kann es durch den User [`cjaegle`](https://phaeton.hbz-nrw.de/gokb/resource/show/org.gokb.cred.User%3A66860), der ausschließlich der CG "KonsBW" zugeordnet ist, nicht bearbeitet werden.

Die Zuordnung von Curatory Groups kann ich leider nicht beurteilen. Sollten hier Änderungen gewünscht sein, bitte ich zwecks Absprache Kontakt mit @darupp oder Vertretung aufzunehmen.

> Jedenfalls funktioniert die Zuordnung, wenn ich den Platformnamen in der GoKB so abändere, dass er mit http:// beginnt.

Die funktionierende Zuordnung bezieht sich dann vermutlich auf ein Paket ohne Curatory Group!?

> Das müssten wir dann denke ich in der GoKB fixen. (?)

Auch das müsste @darupp entscheiden, den ich hier zunächst einmal assigne. Wenn das eilt, bitte ich, ebenfalls Kontakt mit seiner Vertretung aufzunehmen.

Bitte gib mir für das Problemverständnis Rückmeldung, ob ich mit meiner "Diagnose" der fehlenden Übereinstimmung von CGs richtig liege, also insb. ob das Update auch dann funktioniert, wenn Du die CG "hbz" oder "LAS:eR" angibst. Danke.

**Comment by cjaegle** [comment]
Vielleicht reden wir gerade aneinander vorbei: es geht mir gar nicht nur um ein Update eines Paketes, schon gar nicht um das Update eines fremden Paketes,  sondern auch beim Neuanlegen tritt das Problem auf. 
Ich will ein neues Paket einer existierenden Platform zuordnen und habe pötzlich 3 Platformen im System und die Tipps hängen an der falschen Platform. Und wenn ich das richtig deute, ist das bei euch auch passiert, da sind 6 ACS Platformen und eigentlich will man die TIPPS an der einen Platform hängen haben mit Primary URL und Provider. Es wurden aber neue Platformen angelegt (Siehe Review Requests und auch eng beieinander liegende Timestamps bei der Erzeugung)

Ich habe nur versucht ein neues Paket der existierenden Nature Platform (ohne Curatory Group link) zuzuordnen, und das ging nicht, weil der Platformname nicht mit "http" angefangen hat.

Wenn das mit den CGs so ist, dann kann da zusätzlich noch etwas schiefgehen, hat aber mit dem von mir genannten Problem nichts zu tun.

**Comment by cjaegle** [comment]
@philboeselager ich habe aber doch noch eine Frage zu den Curatory Groups. Wird die Angabe der 2. CG in Ygor nur zum Abgleich verwendet, oder sollte die automatisch in einem neu hochgeladenen Paket eingetragen sein?

**Comment by philboeselager** [comment]
> Wird die Angabe der 2. CG in Ygor nur zum Abgleich verwendet, oder sollte die automatisch in einem neu hochgeladenen Paket eingetragen sein?

Seitens Ygor werden beide Curatory Group-Einträge gleich behandelt, d. h. es werden beide Einträge an die GOKb übertragen, um dort evaluiert zu werden.

> wenn ich das richtig sehe, können initial nur Benutzer, die der Gruppe LAS:eR zugeordnet sind Pakete anlegen. Das ist mir bisher nicht aufgefallen, da ich in unserer lokalen Umgebung als Admin hochgeladen habe (mit Zuordnung zu LAS:eR). Ich kann aber kein Paket als Benutzer initial hochladen (403 Antwort).

Hier müsste ich mich erst mit @darupp abstimmen, wie eine Änderung vorzunehmen wäre.

**Comment by hornmo** [comment]
https://github.com/hbz/gokb-phase1/blob/d3981216d8bc23ddf29d8544fbfa4f5b4fea4d7e/server/gokb/grails-app/domain/org/gokb/cred/Platform.groovy#L192

Das Statement muss zwei Zeilen weiter außerhalb der Klammern stehen.

**Comment by philboeselager** [comment]
Umgesetzt in https://github.com/hbz/gokb-phase1/commit/288a25dadeb73053fe72e7fa04dd31237774e31e.
