### ISSUE TITLE
KBART: coverage_notes wird vorausgesetzt

### ISSUE THREAD

**Issue by HebisJC** [hbz/laser-ygor#7]
In der KBART I Spezifikation wird das Feld "coverage_notes" verwendet, in KBART II hat man das Feld in "notes" umbenannt.

Ygor setzt derzeit KBART I voraus, der Export aus dem Statistikserver wird im KBART II ausgeliefert und enthält das Feld nicht mehr.

Hier sollten beide Felder berücksichtigt werden. Fehlermeldung ist angehängt.

![coverage_notes_error](https://cloud.githubusercontent.com/assets/25322798/25948487/f16a5004-3653-11e7-89c0-06cfb6fa688b.png)

**Comment by klodav** [comment]
Version 0.24

Ab dieser Version wird KBART II (also: _notes_) vorausgesetzt.
