### ISSUE TITLE
Unvollständige Übertragung von TIPPs 

### ISSUE THREAD

**Issue by MiriKon** [hbz/laser-ygor#75]
Beim Einspielen von KBART-Dateien in Ygor kommt es beim Senden der Daten an die GOKb immer wieder zu unvollständigen Übertragungen, d.h. in meinem Fall hat eine Titelliste für OECD 329 Titel, welche in die GOKb gespielt werden sollen. Durch Ygor wurden allerdings nur 262 Titel in die GOKb eingespielt.  Was könnte hier das Problem sein? Die Datei, die ich in Ygor hochgeladen habe, habe ich hier angehängt.

[Global_UN_Serials_doi.txt](https://github.com/hbz/laser-ygor/files/2600284/Global_UN_Serials_doi.txt)

**Comment by darupp** [comment]
Works now by magic
