### ISSUE TITLE
Not a Valid Domain Name

### ISSUE THREAD

**Issue by HebisJC** [hbz/laser-ygor#8]
Beim Versuch BioOne-Daten hochzuladen erhalte ich folgende Fehlermeldung:

![not_valid_domain_name](https://cloud.githubusercontent.com/assets/25322798/25949055/7ffca73e-3656-11e7-8737-f8c4c95b7ec4.png)

**Comment by klodav** [comment]
Das Problem hat sich durch den Umbau des URL-Matchings eingeschlichen und wurde behoben.
