### ISSUE TITLE
File Upload doesn't work with Mozilla Firefox

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#80]
File Upload doesn't work with Mozilla Firefox. No new page is rendered, you get back to the upload page.

**Comment by VolkerHBZ** [comment]
works for me. (Firefox 66.0.1 (64-Bit) for Ubuntu

**Comment by croqueGrec09** [comment]
On Ygor-QA, file upload did not work for me. On Ygor-DEV, it worked. Tested today with Firefox 68.0.1 (64-bit) on Windows 10.

**Comment by darupp** [comment]
Reopened, because problem isn't solved. Erratic behaviour. Works on some local browsers, but not on others. Should stay under observation.

**Comment by croqueGrec09** [comment]
In connection with LAS:eR, where this behavior occurres, too, it is suspected that some server settings may play a role as well.

**Comment by darupp** [comment]
Same at the Moment in Chrome with the Jetty Installation on http://phaeton-qa.hbz-nrw.de:9000/ygor/enrichment/process

Same file with the Tomcat Installation works perfectly  http://phaeton-qa.hbz-nrw.de/ygor/enrichment/process

**Comment by darupp** [comment]
Hasn't occurred since we use the Tomcat installation. This problem is obviously a problem with the combination of

  * Multipart file
  * Grails 2
  * Configuration of the runtime environment (Jetty, Tomcat)

Closed for now
