### ISSUE TITLE
Package Sending an GOKb funktioniert nicht

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#84]
Zeitschriften-Package wurde mit Ygor bearbeitet und korrekt angelegt und mit positiver Rückmeldung [result:ok] an GOKb geschickt. Paket wird angelegt, aber in der GOKb fehlen sämtliche Tipps. Package-JSON sieht korrekt aus.

System: phaeton-qa

Zwei Versuche:
https://phaeton-qa.hbz-nrw.de/gokb/resource/show/org.gokb.cred.Package%3A505080
https://phaeton-qa.hbz-nrw.de/gokb/resource/show/org.gokb.cred.Package:505125

[OUP_Ygor_Statusfiles_20190204.zip](https://github.com/hbz/laser-ygor/files/2827949/OUP_Ygor_Statusfiles_20190204.zip)

Maybe the API Structure has changed with Grails 3?

**Comment by philboeselager** [comment]
In den Titel-Daten zu diesem Paket existiert eine Dublette:

- https://phaeton-qa.hbz-nrw.de/gokb/resource/show/org.gokb.cred.JournalInstance:224874
- https://phaeton-qa.hbz-nrw.de/gokb/resource/show/org.gokb.cred.JournalInstance:224860

Dadurch kann der entsprechende Tipp nicht eindeutig zugeordnet werden und die Paket-Verarbeitung bricht ab.

Wie visualisieren wir am besten das Problem, @darupp ?

**Comment by hornmo** [comment]
Der Fehler basiert zum Teil auch auf #87 : 
https://phaeton-qa.hbz-nrw.de/gokb/resource/show/org.gokb.cred.JournalInstance:224874 hat zwei zdb-ids.

**Comment by hornmo** [comment]
Der beste Weg zur Deduplizierung wäre 224874 auf status 'Deleted' setzen, und dann über die action 'Title Merge' alles außer den Identifiern umzuhängen.

**Comment by darupp** [comment]
Okay, werde ich heute noch machen.

**Comment by darupp** [comment]
Was die Visualisierung anbelangt wäre natürlich GOKb-seitig eine entsprechende Meldung notwendig, die auch über die API zurückgegeben werden kann. Ob das möglich ist, weiß ich nicht. Wenn erst NACH der Akzeptanz des JSONs über die API intern der Fehler auftritt, ist natürlich eine API-Antwort nicht möglich.

**Comment by philboeselager** [comment]
Ich schreibe an der entsprechenden Stelle jedenfalls mal das Logging als Warning raus.

**Comment by hornmo** [comment]
Ich bin schon dabei, die Antworten/Fehlermeldungen im IntegrationController zu verbessern. Zur Anzeige wären einige Anpassungen in Ygor notwendig.

**Comment by philboeselager** [comment]
@hornmo Da ich das Ticket bearbeite, würde ich die Änderungen gerne selbst implementieren. Nur die Fehlersuche zu betreiben, ist unbefriedigend. Für Anregungen bin ich selbstverständlich offen und dankbar.

**Comment by philboeselager** [comment]
@hornmo Du kannst mir auch gerne vorgeben, wie die Kommunikation / Schnittstelle zwischen GOKb und Ygor verändert werden soll. Oder wir besprechen das gemeinsam. Ich setze das dann um.

**Comment by hornmo** [comment]
@philboeselager Auf der Seite der GOKb habe ich auf Grund der Probleme mit den doppelten Anfragen (s. #86 ) damit angefangen, das Crossreferencing (zunächst erstmal für Titel) in Jobs unterzubringen. In dem Zuge experimentiere ich im Branch `integration_job` auch mit Synchronisierung der Matching-Funktionen (`find` in TitleLookupService und `Identifier.lookupOrCreateCanonicalIdentifier`) und habe dort auch schon die API-Returns erweitert. Du kannst dir ja mal anschauen, was du davon hältst. Es würde aber auf jeden Fall Sinn machen, uns bezüglich der Returns zu beraten.

**Comment by philboeselager** [comment]
@hornmo Da Du die Lösung ja anscheinend bereits umfangreich umgesetzt hast, wäre es unsinnig, das weiter zu teilen.

Für die Zukunft bitte ich **mindestens** um Absprache, da ich, wie bereits geäußert, keine Lust habe, nur für die Fehlersuche zuständig zu sein.
