### ISSUE TITLE
Multiple concurrent GOKb imports possible

### ISSUE THREAD

**Issue by hornmo** [hbz/laser-ygor#86]
After having sent results once to GOKb, refreshing the site automatically repeats the last upload process. 

While waiting for the import to finish, the submit button is not disabled and therefore multiple concurrent imports requests can be active at the same time.

**Comment by philboeselager** [comment]
Fixed in https://github.com/hbz/laser-ygor/commit/5a0b9f92eec7b8806f2dae0b42b79c490c926334 and in https://github.com/hbz/laser-ygor/commit/79f00a36911473c721d951483c0e3e7b6095460d. Closing.
