### ISSUE TITLE
Multiple ZDB results for a single ISSN getting combined in JSON

### ISSUE THREAD

**Issue by hornmo** [hbz/laser-ygor#87]
Encountered in: https://www.tandfonline.com/page/title-lists -> Medicine & Dentistry
Related lines:

Title | PISSN | EISSN
-- | -- | --
Electro- and Magnetobiology | 1061-9526 |  
Electromagnetic Biology and Medicine | 1536-8378 | 1536-8386

http://services.dnb.de/sru/zdb?version=1.1&operation=searchRetrieve&query=dnb.iss%3D1061-9526%20and%20dnb.frm=O&maximumRecords=2&recordSchema=PicaPlus-xml

http://services.dnb.de/sru/zdb?version=1.1&operation=searchRetrieve&query=dnb.iss%3D1536-8386%20and%20dnb.frm=O&maximumRecords=2&recordSchema=PicaPlus-xml

First entry is missing the initially provided pISSN:

```
      {
         "coverage": [{
            "coverageDepth": "fulltext",
            "startIssue": "1",
            "endVolume": "20",
            "endDate": "2001-12-31 23:59:59.000",
            "startVolume": "16",
            "coverageNote": "",
            "embargo": "",
            "endIssue": "3",
            "startDate": "1997-01-01 00:00:00.000"
         }],
         "accessStartDate": "",
         "accessEndDate": "",
         "medium": "Electronic",
         "title": {
            "identifiers": [
               {
                  "type": "zdb",
                  "value": "2026727-7"
               },
               {
                  "type": "eissn",
                  "value": "1536-8386"
               }
            ],
            "name": "Electro- and magnetobiology",
            "type": "Serial"
         },
         "platform": {
            "name": "Taylor & Francis Online",
            "primaryUrl": "http://www.tandfonline.com"
         },
         "url": "https://www.tandfonline.com/openurl?genre=journal&stitle=iebm19",
         "status": "Current"
      },
```
Second entry is combining eISSNs & ZBD-IDs of two titles into one:
```
      {
         "coverage": [{
            "coverageDepth": "fulltext",
            "startIssue": "1",
            "endVolume": "",
            "endDate": "",
            "startVolume": "21",
            "coverageNote": "",
            "embargo": "",
            "endIssue": "",
            "startDate": "2002-01-01 00:00:00.000"
         }],
         "accessStartDate": "",
         "accessEndDate": "",
         "medium": "Electronic",
         "title": {
            "identifiers": [
               {
                  "type": "zdb",
                  "value": "2588120-6"
               },
               {
                  "type": "eissn",
                  "value": "1536-8386"
               },
               {
                  "type": "zdb",
                  "value": "2026727-7"
               },
               {
                  "type": "eissn",
                  "value": "1536-8386"
               }
            ],
            "name": "Electro- and magnetobiology",
            "type": "Serial"
         },
         "platform": {
            "name": "Taylor & Francis Online",
            "primaryUrl": "http://www.tandfonline.com"
         },
         "url": "https://www.tandfonline.com/openurl?genre=journal&stitle=iebm20",
         "status": "Current"
      },
```

**Comment by hornmo** [comment]
I have tested a bit more and would strongly advise not to import any title lists without an existing zdb-id to GOKb at this time!

**Comment by jorol** [comment]
This is an error in the bibliographic database. We will correct the records and run an analysis to check for other ISSN with multiple entries.

**Comment by jorol** [comment]
Have you tried to extend the SRU request with the journal title to narrow the result set?

Example:

http://services.dnb.de/sru/zdb?version=1.1&operation=searchRetrieve&recordSchema=PicaPlus-xml&query=dnb.iss%3D1536-8386%20and%20dnb.tit%3D%22Electromagnetic%20biology%20and%20medicine%22%20and%20dnb.frm=O

**Comment by darupp** [comment]
Thank you, this should help, especially the search by dnb.tst, as the title in the KBART file doesn't match necessarily the one in ZDB so that we would have lots of mismatches. @hornmo, @philboeselager and me talked about this issue in a web conference. The solution steps would be:

1) If we get multiple records, do a second SRU call like @joroll recommended with dnb.tst

2) If there are still multiple records,  give back an understandable error message / error code and expunge the title from the JSON

3) Reworking XML Parsing  so that tags will only be read if they belong to the correct record.

**Comment by philboeselager** [comment]
Fixed. As a side effect, the `publisher_history` is also reduced to the length of 1. Ready to deploy.

**Comment by jorol** [comment]
The second query with the "publicationTitle" should use the index `dnb.tst` not `dnb.tit`, see https://github.com/hbz/laser-ygor/commit/29f40ca9ec01d15649b616ac25cd59ea322243a1?diff=unified#diff-d367568b426013254dcb895c9b2206d1R52

**Comment by philboeselager** [comment]
Thanks, @jorol . Fixed.
