### ISSUE TITLE
Import/Export erweiterter Coverage Informationen

### ISSUE THREAD

**Issue by cjaegle** [hbz/laser-ygor#9]
Bei dem Versuch einen EZB KBart Export mit Ygor zu verarbeiten wurden bei den coverage Daten nur startDate und endDate mit in den Json Export ausgegeben, die anderen coverage Informationen waren nicht mit dabei. Ist das ein Problem mit dem verwendeten KBart Export oder fehlt die Verarbeitung dieser Felder?
[springer2015ezb_500.zip](https://github.com/hbz/laser-ygor/files/1088347/springer2015ezb_500.zip)

**Comment by klodav** [comment]
Korrekt sollten die folgenden Felder aus den KBART-Dateien verarbeitet werden:

```
    date_first_issue_online
    date_last_issue_online
    num_first_vol_online
    num_last_vol_online
    num_first_issue_online
    num_last_issue_online
    title_url
    embargo_info
    coverage_depth
    coverage_notes
```
In der Debug-Datei ist erkennbar, dass die Werte in der aktuellen Version (0.23) zwar initial erfasst, aber entweder nicht korrekt verarbeitet und später überschrieben werden.

Danke für den Hinweis.

**Comment by klodav** [comment]
Version 24

Die Feldinhalte werden wieder korrekt verarbeitet.
