### ISSUE TITLE
Journals: title_id is not imported in title JSON

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#98]
After uploading a journal file, you can select the id namespace for *title_id*. (Usually, this will be a proprietary namespace you first have to create in GOKb).

These values are not imported into the title JSON.

[ACS KBART_ygor_neu.txt](https://github.com/hbz/laser-ygor/files/3053081/ACS.KBART_ygor_neu.txt)

Please test also with ebook title lists.

**Comment by philboeselager** [comment]
Confirmed. Having processed some ACS data with new proprietary namespace `inid_acs`, the titles.json shows the content of `title_id` in the `ezb` identifier field.

**Comment by philboeselager** [comment]
> Having processed some ACS data with new proprietary namespace inid_acs, the titles.json shows the content of title_id in the ezb identifier field.

Looks like the EZB IDs are simply put into the column `title_id` in this Kbart table. For example:

- Kbart:
  - `publication_title`: "ACS Biomaterials Science & Engineering"
  - `title_id`: "227628"
  - `zdb_id`: "2806065-9"
- EZB query: http://rzblx1.uni-regensburg.de/ezeit/searchres.phtml?bibid=HBZ&xmloutput=1&xmlv=3&jq_type1=ZD&jq_term1=2806065-9
- EZB query result: 
`<journals>`
`  <journal jourid="227628">`
`    <title>ACS Biomaterials Science &amp; Engineering </title>`
`  </journal>`
`</journals>`

So, this is a faulty Kbart. There is nothing to be done about this case in Ygor. Would you agree, @darupp ? 

Still have to find out, why proprietary namespace data is missing in Ygor's processing result.

**Comment by philboeselager** [comment]
Included in Ygor v. 0.57 and deployed on phaeton-dev.
